<?php

return [
    'block_types' => [
        'hero' => 'Hero banner',
        'stats' => 'Impact statistics',
        'rich_text' => 'Rich text',
        'media_text' => 'Image and text',
        'cards' => 'Card grid',
        'ways_to_give' => 'Ways to Give',
        'causes' => 'Programs and causes',
        'events' => 'Upcoming events',
        'testimonials' => 'Testimonials',
        'team' => 'Leadership and team',
        'partners' => 'Partner organizations',
        'faq' => 'Frequently asked questions',
        'timeline' => 'Timeline or process',
        'gallery' => 'Photo gallery',
        'video' => 'Video',
        'cta' => 'Call to action',
        'newsletter' => 'Newsletter signup',
        'spacer' => 'Spacing',
        'custom_html' => 'Custom HTML',
    ],

    'simple_sections' => [
        'hero' => ['label' => 'Hero banner', 'icon' => 'fa-image', 'description' => 'A large opening image with a message and buttons.'],
        'rich_text' => ['label' => 'Text section', 'icon' => 'fa-align-left', 'description' => 'A heading and formatted body copy.'],
        'media_text' => ['label' => 'Image and text', 'icon' => 'fa-columns', 'description' => 'Tell a story beside a photograph.'],
        'stats' => ['label' => 'Impact statistics', 'icon' => 'fa-bar-chart', 'description' => 'Show important numbers and short labels.'],
        'cards' => ['label' => 'Cards or projects', 'icon' => 'fa-th-large', 'description' => 'A visual grid of programs, projects, or stories.'],
        'ways_to_give' => ['label' => 'Ways to Give', 'icon' => 'fa-gift', 'description' => 'Offer managed donation causes, Zakat, and child sponsorship without entering links.'],
        'causes' => ['label' => 'Programs and causes', 'icon' => 'fa-heart', 'description' => 'Automatically display active programs.'],
        'events' => ['label' => 'Upcoming events', 'icon' => 'fa-calendar', 'description' => 'Automatically display upcoming events.'],
        'testimonials' => ['label' => 'Community stories', 'icon' => 'fa-quote-left', 'description' => 'Automatically display approved testimonials.'],
        'team' => ['label' => 'Leadership and team', 'icon' => 'fa-users', 'description' => 'Automatically display published board or team members.'],
        'partners' => ['label' => 'Partner organizations', 'icon' => 'fa-handshake', 'description' => 'Show a polished wall of partner logos with optional website links.'],
        'faq' => ['label' => 'Questions and answers', 'icon' => 'fa-circle-question', 'description' => 'Add accessible expandable answers to common questions.'],
        'timeline' => ['label' => 'Timeline or process', 'icon' => 'fa-timeline', 'description' => 'Explain milestones, history, or a step-by-step process.'],
        'gallery' => ['label' => 'Photo gallery', 'icon' => 'fa-images', 'description' => 'Display selected photos or published gallery images.'],
        'video' => ['label' => 'Video', 'icon' => 'fa-circle-play', 'description' => 'Embed a YouTube or Vimeo video, or play an uploaded video.'],
        'cta' => ['label' => 'Call to action', 'icon' => 'fa-bullhorn', 'description' => 'Invite visitors to donate, volunteer, or learn more.'],
        'newsletter' => ['label' => 'Newsletter signup', 'icon' => 'fa-envelope', 'description' => 'Let visitors subscribe for updates.'],
    ],

    /*
     * Automatic sections keep presentation copy in the block while selecting
     * their cards from managed content. These labels are shared by both page
     * editors so an editor never needs to type a model name or edit JSON.
     */
    'automatic_sources' => [
        'cards' => [
            'manual' => 'Cards I enter here',
            'projects' => 'Managed projects',
            'category' => 'Pages from a category',
        ],
        'causes' => [
            'category' => 'Published programs from a category',
        ],
        'events' => [
            'events' => 'Published events and news',
        ],
        'testimonials' => [
            'testimonials' => 'Approved community stories',
        ],
        'team' => [
            'team' => 'Published board and team members',
        ],
        'gallery' => [
            'gallery' => 'Published gallery photos',
            'manual' => 'Photos I enter here',
        ],
    ],

    'automatic_sort_options' => [
        'featured' => 'Featured order',
        'newest' => 'Newest first',
        'oldest' => 'Oldest first',
        'title' => 'Title A–Z',
    ],

    'default_content' => [
        'hero' => [
            'eyebrow' => 'Urgent initiative',
            'heading' => 'A clear, human headline',
            'body' => 'Explain the impact of this initiative in a concise sentence.',
            'primary_label' => 'Donate now',
            'primary_url' => '/donate',
            'secondary_label' => '',
            'secondary_url' => '',
            'image' => '',
            'overlay_opacity' => 64,
            'autoplay' => true,
            'interval' => 6000,
            'pause_on_hover' => true,
            'slides' => [[
                'eyebrow' => 'Urgent initiative',
                'heading' => 'A clear, human headline',
                'body' => 'Explain the impact of this initiative in a concise sentence.',
                'primary_label' => 'Donate now',
                'primary_url' => '/donate',
                'secondary_label' => '',
                'secondary_url' => '',
                'report_label' => '',
                'report_url' => '',
                'image' => '',
                'overlay_opacity' => 64,
            ]],
        ],
        'stats' => [
            'heading' => 'Our impact',
            'animation_enabled' => true,
            'animation_type' => 'count_up',
            'animation_duration' => 1600,
            'animation_delay' => 120,
            'items' => [
                ['value' => '0', 'label' => 'Lives impacted'],
                ['value' => '0', 'label' => 'Active projects'],
                ['value' => '0%', 'label' => 'Funds to field'],
            ],
        ],
        'rich_text' => [
            'eyebrow' => '',
            'heading' => 'Section heading',
            'body' => '<p>Add your content here.</p>',
        ],
        'media_text' => [
            'eyebrow' => '',
            'heading' => 'Tell a meaningful story',
            'body' => '<p>Add your story here.</p>',
            'image' => '',
            'image_alt' => '',
            'image_position' => 'left',
            'link_label' => '',
            'link_url' => '',
        ],
        'cards' => [
            'eyebrow' => '', 'heading' => 'Featured stories', 'body' => '',
            'content_source' => 'manual', 'selection_mode' => 'automatic',
            'selected_items' => [], 'sort' => 'featured', 'limit' => 3,
            'item_link_label' => 'Learn more', 'view_all_label' => '',
            'view_all_url' => '', 'empty_state' => 'New items will appear here soon.',
            'items' => [],
        ],
        'ways_to_give' => [
            'eyebrow' => 'Ways to give',
            'heading' => 'Choose how you would like to help',
            'body' => 'Select a trusted giving option and continue securely.',
            'layout' => 'card_grid',
            'selection_mode' => 'automatic',
            'selected_items' => [],
            'project_uuid' => '',
            'link_label' => 'Give now',
            'empty_state' => 'Giving options are being updated. Please check again soon.',
        ],
        'causes' => [
            'eyebrow' => 'Our work', 'heading' => 'Our programs', 'body' => '',
            'content_source' => 'category', 'category_slug' => 'our-causes',
            'selection_mode' => 'automatic', 'selected_items' => [],
            'sort' => 'featured', 'limit' => 3, 'item_link_label' => 'Learn more',
            'view_all_label' => 'View all programs', 'view_all_url' => '/category/our-causes',
            'empty_state' => 'Published programs will appear here automatically.',
        ],
        'events' => [
            'eyebrow' => 'Get involved', 'heading' => 'Upcoming events', 'body' => '',
            'content_source' => 'events', 'selection_mode' => 'automatic',
            'selected_items' => [], 'sort' => 'featured', 'limit' => 3,
            'item_link_label' => 'Read more', 'view_all_label' => 'View all events',
            'view_all_url' => '/events',
            'empty_state' => 'Upcoming events and field updates will appear here automatically.',
        ],
        'testimonials' => [
            'eyebrow' => 'Community voices', 'heading' => 'Stories of change', 'body' => '',
            'content_source' => 'testimonials', 'selection_mode' => 'automatic',
            'selected_items' => [], 'sort' => 'featured', 'limit' => 3,
            'empty_state' => 'Approved community stories will appear here automatically.',
        ],
        'team' => [
            'eyebrow' => 'Our people', 'heading' => 'Leadership and team',
            'body' => 'Meet the people responsible for our mission and governance.',
            'content_source' => 'team', 'selection_mode' => 'automatic',
            'selected_items' => [], 'sort' => 'featured', 'limit' => 12,
            'item_link_label' => 'View profile',
            'empty_state' => 'Published board and team members will appear here automatically.',
            'items' => [],
        ],
        'partners' => ['eyebrow' => '', 'heading' => 'Partner Organizations', 'body' => '', 'items' => []],
        'faq' => ['eyebrow' => 'Helpful answers', 'heading' => 'Frequently asked questions', 'body' => '', 'items' => [
            ['heading' => 'Add a question', 'body' => 'Add the answer here.'],
        ]],
        'timeline' => ['eyebrow' => 'Our journey', 'heading' => 'Milestones', 'body' => '', 'items' => [
            ['heading' => 'First milestone', 'body' => 'Describe what happened and why it mattered.'],
        ]],
        'gallery' => [
            'eyebrow' => 'In pictures', 'heading' => 'Photo gallery', 'body' => '',
            'content_source' => 'gallery', 'selection_mode' => 'automatic',
            'selected_items' => [], 'sort' => 'featured', 'limit' => 12,
            'view_all_label' => 'View all photos', 'view_all_url' => '/gallery',
            'empty_state' => 'Published gallery photos will appear here automatically.',
            'items' => [],
        ],
        'video' => [
            'eyebrow' => '',
            'heading' => 'Watch our story',
            'body' => '',
            'video_url' => '',
            'poster' => '',
            'caption' => '',
        ],
        'cta' => [
            'eyebrow' => '',
            'heading' => 'Help create lasting change',
            'body' => 'Your support can transform a community.',
            'primary_label' => 'Donate now',
            'primary_url' => '/donate',
        ],
        'newsletter' => [
            'heading' => 'Stories worth sharing',
            'body' => 'Receive field updates and opportunities to help.',
            'button_label' => 'Subscribe',
        ],
        'spacer' => ['size' => 'medium'],
        'custom_html' => ['html' => ''],
    ],
];
