@extends('admin.layouts.master')

@section('content')
<style>
    .igf-customizer{--orange:#f26322;--brown:#8c3d0a;--ink:#25282a;--muted:#6d6d69;--line:#e7e2dc;max-width:1380px;margin:0 auto;padding:30px 24px 70px;color:var(--ink);font-family:'Hanken Grotesk',Arial,sans-serif}.igf-customizer *{box-sizing:border-box}
    .customizer-head{display:flex;align-items:flex-start;justify-content:space-between;gap:24px;margin-bottom:24px}.customizer-head h1{margin:0;font:700 clamp(38px,4vw,58px)/1.05 'Literata',Georgia,serif;letter-spacing:-.035em}.customizer-head p{max-width:720px;margin:9px 0 0;color:var(--muted);font-size:15px;line-height:1.6}.customizer-head__actions{display:flex;align-items:center;gap:10px}.customizer-status{display:none;color:#966017;font-size:12px;font-weight:800}.customizer-status.is-visible{display:inline}.igf-btn{display:inline-flex;min-height:43px;align-items:center;justify-content:center;gap:8px;border:1px solid #d9d2ca;border-radius:8px;padding:8px 16px;background:#fff;color:#4a4540;font-size:13px;font-weight:800;text-decoration:none;cursor:pointer}.igf-btn:hover{border-color:var(--orange);color:var(--brown)}.igf-btn--primary{border-color:var(--orange);background:var(--orange);color:#fff}.igf-btn--primary:hover{background:var(--brown);color:#fff}.igf-btn--quiet{background:#f7f4f1}.igf-btn:focus-visible{outline:3px solid rgba(242,99,34,.22);outline-offset:2px}
    .customizer-tools{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:11px;margin-bottom:22px}.customizer-tool{display:grid;min-height:118px;align-content:space-between;gap:14px;border:1px solid var(--line);border-radius:12px;padding:16px;background:#fff;color:var(--ink);text-decoration:none;box-shadow:0 7px 22px rgba(37,40,42,.035);transition:.18s}.customizer-tool:hover{transform:translateY(-2px);border-color:#efb68c;box-shadow:0 11px 25px rgba(37,40,42,.07)}.customizer-tool i{color:var(--orange);font-size:23px}.customizer-tool strong{display:block;margin-bottom:3px;font:650 15px 'Literata',Georgia,serif}.customizer-tool span{color:var(--muted);font-size:11px;line-height:1.45}
    .customizer-guide{margin:-8px 0 20px;border:1px solid #f0c5a5;border-radius:11px;background:#fff8f2}.customizer-guide summary{padding:14px 17px;color:var(--brown);font-size:13px;font-weight:850;cursor:pointer}.customizer-guide ol{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;margin:0;padding:0 17px 17px;counter-reset:steps;list-style:none}.customizer-guide li{position:relative;padding:11px 11px 11px 38px;border-radius:8px;background:#fff;color:#5f5953;font-size:11px;line-height:1.45}.customizer-guide li::before{position:absolute;top:10px;left:10px;display:grid;width:20px;height:20px;place-content:center;border-radius:50%;background:var(--orange);color:#fff;content:counter(steps);counter-increment:steps;font-size:10px;font-weight:900}.customizer-guide strong{display:block;color:var(--ink)}
    .customizer-preview{margin-bottom:24px;border:1px solid var(--line);border-radius:14px;background:#fff;box-shadow:0 8px 26px rgba(37,40,42,.045)}.customizer-preview__head{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:15px 18px;border-bottom:1px solid var(--line)}.customizer-preview__head h2{margin:0;font:650 20px 'Literata',Georgia,serif}.customizer-preview__head p{margin:4px 0 0;color:var(--muted);font-size:12px}.customizer-preview__controls{display:flex;align-items:center;gap:7px}.preview-page{height:38px;max-width:190px;border:1px solid #ded8d1;border-radius:7px;padding:0 30px 0 10px;background:#fff;color:#4d4844;font-size:12px;font-weight:750}.preview-device{display:grid;width:38px;height:38px;place-content:center;border:1px solid #ded8d1;border-radius:7px;background:#fff;color:#69625c;cursor:pointer}.preview-device.is-active{border-color:var(--orange);background:#fff2e8;color:var(--brown)}.customizer-preview__stage{display:flex;min-height:390px;justify-content:center;overflow:auto;padding:18px;background:#eeeae6}.customizer-preview iframe{width:100%;height:370px;border:1px solid #cac4bd;border-radius:7px;background:#fff;box-shadow:0 7px 22px rgba(0,0,0,.08);transition:width .2s ease}
    .customizer-workspace{display:grid;grid-template-columns:230px minmax(0,1fr);align-items:start;gap:22px}.customizer-nav{position:sticky;top:18px;display:grid;gap:5px}.customizer-nav__search{margin-bottom:7px}.customizer-nav__search label{display:block;margin-bottom:6px;font-size:11px;font-weight:800;letter-spacing:.05em;text-transform:uppercase}.customizer-nav__search input{width:100%;height:42px;border:1px solid #d7d1ca;border-radius:8px;padding:8px 11px}.customizer-nav a{display:flex;align-items:center;justify-content:space-between;gap:8px;border-radius:7px;padding:10px 12px;color:#4b4b47;text-decoration:none}.customizer-nav a:hover{background:#fff2ea;color:var(--brown)}.customizer-nav small{display:grid;min-width:22px;height:22px;place-content:center;border-radius:999px;background:#ece8e4;color:#726c66;font-size:10px}.customizer-locale{margin-top:10px;padding:14px;border:1px solid var(--line);border-radius:10px;background:#fff}.customizer-locale label{display:block;margin-bottom:6px;font-size:11px;font-weight:800;text-transform:uppercase}.customizer-locale select{width:100%;height:42px;border:1px solid #d7d1ca;border-radius:7px;padding:8px;background:#fff}
    .customizer-groups{display:grid;gap:14px}.customizer-card{border:1px solid var(--line);border-radius:12px;background:#fff;box-shadow:0 7px 22px rgba(37,40,42,.035)}.customizer-card[hidden]{display:none}.customizer-card>summary{display:grid;grid-template-columns:1fr auto;align-items:center;gap:18px;padding:19px 21px;cursor:pointer;list-style:none}.customizer-card>summary::-webkit-details-marker{display:none}.customizer-card>summary h2{margin:0;font:650 23px 'Literata',Georgia,serif}.customizer-card>summary p{margin:5px 0 0;color:var(--muted);font-size:13px}.customizer-card>summary i{color:var(--orange);transition:transform .18s}.customizer-card[open]>summary i{transform:rotate(180deg)}.customizer-fields{border-top:1px solid var(--line);padding:4px 21px}.donation-builder{display:grid;grid-template-columns:1fr auto;align-items:center;gap:18px;margin:0 -21px;padding:18px 21px;border-bottom:1px solid #eadfd6;background:#fff8f2}.donation-builder strong{display:block;margin-bottom:4px;color:var(--brown);font-size:14px}.donation-builder p{margin:0;color:#6e625b;font-size:11px;line-height:1.5}.donation-builder__actions{display:flex;flex-wrap:wrap;gap:8px}.customizer-field{display:grid;grid-template-columns:minmax(170px,.75fr) minmax(280px,1.5fr) auto;align-items:start;gap:18px;padding:17px 0;border-bottom:1px solid #f1eee9}.customizer-field:last-child{border:0}.customizer-field>label,.customizer-field__label{padding-top:10px;font-weight:750}.customizer-field>label small,.customizer-field__label small{display:block;margin-top:5px;color:#8a837c;font-size:10px;font-weight:600;line-height:1.45}.customizer-control input:not([type=checkbox],[type=radio]),.customizer-control textarea{width:100%;border:1px solid #d7d1ca;border-radius:7px;padding:10px 11px;background:#fff;color:var(--ink)}.customizer-control textarea{min-height:90px;resize:vertical}.customizer-control input[type=color]{height:46px;padding:4px}.customizer-control input:focus,.customizer-control textarea:focus{outline:3px solid rgba(242,99,34,.16);border-color:var(--orange)}.customizer-check{display:flex;min-height:42px;align-items:center;gap:9px;margin:0}.customizer-check input{width:19px;height:19px;accent-color:var(--orange)}.customizer-reset{margin-top:8px;border:0;background:transparent;color:var(--brown);font-size:11px;font-weight:750;cursor:pointer}.customizer-reset:hover{text-decoration:underline}.customizer-no-results{display:none;padding:50px;border:1px dashed #d7d1ca;border-radius:12px;background:#fff;text-align:center}.customizer-no-results.is-visible{display:block}
    .customizer-presets{display:grid;grid-template-columns:repeat(auto-fit,minmax(112px,1fr));gap:8px;margin:0;padding:0;border:0}.customizer-preset{position:relative;margin:0;cursor:pointer}.customizer-preset input{position:absolute;width:1px;height:1px;opacity:0;pointer-events:none}.customizer-preset span{display:grid;min-height:58px;place-content:center;border:1px solid #d7d1ca;border-radius:9px;padding:10px;background:#faf9f7;color:#5f5953;font-size:12px;font-weight:800;text-align:center;transition:.15s ease}.customizer-preset:hover span{border-color:#efb68c;background:#fff7f1}.customizer-preset input:checked+span{border-color:var(--orange);background:#fff0e4;color:var(--brown);box-shadow:inset 0 0 0 1px var(--orange)}.customizer-preset input:focus-visible+span{outline:3px solid rgba(242,99,34,.22);outline-offset:2px}
    .media-setting{display:grid;grid-template-columns:112px minmax(0,1fr);gap:14px}.media-setting__preview{display:grid;width:112px;height:84px;overflow:hidden;place-content:center;border:1px solid #ded8d2;border-radius:9px;background:#f1efec}.media-setting__preview img{width:112px;height:84px;object-fit:cover}.media-setting__actions{display:flex;flex-wrap:wrap;align-content:center;gap:8px}.media-setting__advanced{width:100%}.media-setting__advanced summary{color:#756e68;font-size:11px;cursor:pointer}.media-setting__advanced input{margin-top:8px;font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:11px}.customizer-save{position:sticky;z-index:4;bottom:0;display:flex;align-items:center;justify-content:flex-end;gap:12px;padding:17px 0;background:linear-gradient(transparent,#f5f5f3 32%)}
    .media-modal[hidden]{display:none}.media-modal{position:fixed;z-index:10000;inset:0;display:grid;place-items:center;padding:22px;background:rgba(25,28,29,.62)}.media-modal__dialog{display:grid;width:min(940px,100%);max-height:min(760px,92vh);grid-template-rows:auto auto minmax(0,1fr);overflow:hidden;border-radius:15px;background:#fff;box-shadow:0 24px 70px rgba(0,0,0,.28)}.media-modal__head{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:19px 21px;border-bottom:1px solid var(--line)}.media-modal__head h2{margin:0;font:650 25px 'Literata',Georgia,serif}.media-modal__close{display:grid;width:40px;height:40px;place-content:center;border:0;border-radius:8px;background:#f2efec;cursor:pointer}.media-modal__search{padding:14px 20px;border-bottom:1px solid var(--line)}.media-modal__search input{width:100%;height:44px;border:1px solid #d7d1ca;border-radius:8px;padding:9px 12px}.media-modal__grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));align-content:start;gap:12px;overflow:auto;padding:18px 20px 24px}.media-choice{overflow:hidden;border:1px solid var(--line);border-radius:10px;background:#fff;text-align:left;cursor:pointer}.media-choice:hover,.media-choice:focus-visible{border-color:var(--orange);outline:3px solid rgba(242,99,34,.15)}.media-choice img{display:block;width:100%;aspect-ratio:4/3;object-fit:cover;background:#eee}.media-choice span{display:block;overflow:hidden;padding:10px;color:#4d4844;font-size:11px;font-weight:700;text-overflow:ellipsis;white-space:nowrap}.media-empty{grid-column:1/-1;padding:48px;text-align:center;color:var(--muted)}
    .customizer-read-only{margin:0 0 22px;padding:14px 17px;border:1px solid #edcf9f;border-radius:10px;background:#fff8e8;color:#74501d;font-size:13px;line-height:1.55}.customizer-read-only strong{display:block;margin-bottom:2px;color:#56370d}.customizer-control :disabled{cursor:not-allowed;opacity:.72}
    .payment-provider-status{margin:0 -21px;padding:18px 21px;border-bottom:1px solid #eadfd6;background:#fbfaf8}.payment-provider-status__head{display:flex;align-items:start;justify-content:space-between;gap:18px;margin-bottom:12px}.payment-provider-status__head strong{display:block;color:var(--ink);font-size:14px}.payment-provider-status__head p{max-width:700px;margin:4px 0 0;color:var(--muted);font-size:11px;line-height:1.5}.payment-provider-status__head span{border-radius:999px;padding:4px 9px;background:#ece8e4;color:#645e58;font-size:9px;font-weight:850;letter-spacing:.04em;text-transform:uppercase}.payment-provider-status ul{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px;margin:0;padding:0;list-style:none}.payment-provider-status li{display:grid;grid-template-columns:1fr auto;align-items:start;gap:9px;border:1px solid #e2ddd7;border-radius:9px;padding:12px;background:#fff}.payment-provider-status li>div>strong{display:block;color:var(--ink);font-size:13px}.payment-provider-status li small{display:block;margin-top:4px;color:#766f69;font-size:10px;line-height:1.45}.payment-provider-status li>span{display:inline-flex;align-items:center;gap:5px;border-radius:999px;padding:4px 7px;background:#f4ece6;color:#8a3f13;font-size:9px;font-weight:850;white-space:nowrap}.payment-provider-status li.is-ready>span{background:#e8f5ec;color:#27713c}
    @media(max-width:1150px){.customizer-tools{grid-template-columns:repeat(3,1fr)}}
    @media(max-width:1100px){.igf-customizer{padding-inline:14px}.customizer-head{flex-direction:column}.customizer-head__actions{width:100%;flex-wrap:wrap}.customizer-guide ol{grid-template-columns:1fr 1fr}.customizer-workspace{grid-template-columns:1fr}.customizer-nav{position:static;grid-template-columns:repeat(2,minmax(0,1fr))}.customizer-nav__search,.customizer-locale{grid-column:1/-1}.customizer-field{grid-template-columns:1fr}.customizer-field>label{padding-top:0}.customizer-reset{justify-self:start}.customizer-preview__head{align-items:flex-start;flex-direction:column}.donation-builder{grid-template-columns:1fr}.payment-provider-status ul{grid-template-columns:1fr}}
    @media(max-width:560px){.customizer-guide ol{grid-template-columns:1fr}.customizer-tools{grid-template-columns:repeat(2,1fr)}.customizer-tool{min-height:105px}.customizer-nav{grid-template-columns:1fr}.customizer-nav__search,.customizer-locale{grid-column:auto}.media-setting{grid-template-columns:84px minmax(0,1fr)}.media-setting__preview,.media-setting__preview img{width:84px;height:70px}.customizer-preview__controls{flex-wrap:wrap}.customizer-preview__stage{padding:9px}.media-modal{padding:9px}.media-modal__grid{grid-template-columns:repeat(2,minmax(0,1fr));padding-inline:12px}}
</style>

@php
    $admin = auth('admin')->user();
    $permissions = app(\App\Http\Middleware\Permission::class);
    $canUse = fn (string $route): bool => $permissions->allows($admin, $route);
    $canUpdateSettings = $canUse('site.settings.update');
    $canResetSettings = $canUse('site.settings.destroy');
    $isSettingsViewOnly = !$canUpdateSettings && !$canResetSettings;
    $toolCards = [
        ['route' => 'page.index', 'label' => 'Pages & sections', 'description' => 'Edit every page visually', 'icon' => 'fa-file-text-o', 'url' => route('page.index')],
        ['route' => 'site.settings.index', 'label' => 'Design & layout', 'description' => 'Resize headings, images and cards', 'icon' => 'fa-paint-brush', 'url' => route('site.settings.index', ['locale' => $locale]).'#settings-design'],
        ['route' => 'site.settings.index', 'label' => 'Donation experience', 'description' => 'Layout, amounts, wording and help', 'icon' => 'fa-heart-o', 'url' => route('site.settings.index', ['locale' => $locale]).'#settings-donation_page'],
        ['route' => 'page.menu.index', 'label' => 'Navigation', 'description' => 'Header and footer menus', 'icon' => 'fa-sitemap', 'url' => route('page.menu.index')],
        ['route' => 'media.index', 'label' => 'Media Library', 'description' => 'Images and documents', 'icon' => 'fa-picture-o', 'url' => route('media.index')],
        ['route' => 'reusable-blocks.index', 'label' => 'Reusable sections', 'description' => 'Update shared content once', 'icon' => 'fa-clone', 'url' => route('reusable-blocks.index')],
        ['route' => 'seo.index', 'label' => 'Search & sharing', 'description' => 'Search previews, URLs and sharing', 'icon' => 'fa-search', 'url' => route('seo.index')],
        ['route' => 'content.trash.index', 'label' => 'Trash & recovery', 'description' => 'Restore deleted content', 'icon' => 'fa-trash', 'url' => route('content.trash.index')],
    ];
    $toolCards = array_values(array_filter($toolCards, fn (array $tool): bool => $canUse($tool['route'])));
    $previewPages = [
        'Home' => route('frontend.home'),
        'Contact' => route('frontend.contactUs'),
        'Donate' => route('frontend.donate.index'),
        'Sponsor a child' => route('frontend.sponsor_child'),
        'Volunteer' => route('frontend.volunteer_registration.index'),
        'Zakat' => route('frontend.zakat'),
        'Gallery' => route('frontend.gallery'),
        'Annual reports' => route('frontend.annual_report.index'),
        'Search' => route('search'),
        'Member sign in' => route('showLogin'),
    ];
@endphp

<main class="igf-customizer">
    <header class="customizer-head">
        <div><h1>Website Customizer</h1><p>Change the website without code. Start with a task below, preview the public website, then open only the settings section you need.</p></div>
        <div class="customizer-head__actions">@if($canUpdateSettings)<span id="customizer-status" class="customizer-status" role="status" aria-live="polite">Unsaved changes</span>@endif<a class="igf-btn" href="{{ route('frontend.home') }}" target="_blank" rel="noopener"><i class="fa fa-external-link" aria-hidden="true"></i> Open website</a>@if($canUpdateSettings)<button class="igf-btn igf-btn--primary" type="submit" form="customizer-form"><i class="fa fa-save" aria-hidden="true"></i> Save changes</button>@endif</div>
    </header>

    @if($isSettingsViewOnly)
        <div class="customizer-read-only" role="status"><strong>Read-only access</strong>You can review settings and preview the public website, but your role cannot save or reset website settings.</div>
    @elseif(!$canUpdateSettings)
        <div class="customizer-read-only" role="status"><strong>Limited settings access</strong>You can review current values and use permitted reset actions, but your role cannot save changes.</div>
    @endif

    <details class="customizer-guide"><summary><i class="fa fa-question-circle" aria-hidden="true"></i> New here? Follow these five simple steps</summary><ol><li><strong>Choose your task</strong>Use one shortcut below instead of looking through technical menus.</li><li><strong>Edit a page</strong>Open Pages &amp; sections, choose a page, then click text or Add section.</li><li><strong>Choose images</strong>Use Choose image; upload files to the Media Library first when needed.</li><li><strong>Preview safely</strong>Select the page and device here, then refresh after saving.</li><li><strong>Publish confidently</strong>Check Search &amp; sharing, save, and use Trash &amp; recovery if you make a mistake.</li></ol></details>

    <nav class="customizer-tools" aria-label="Website customization tools">
        @foreach($toolCards as $tool)<a class="customizer-tool" href="{{ $tool['url'] }}"><i class="fa {{ $tool['icon'] }}" aria-hidden="true"></i><span><strong>{{ $tool['label'] }}</strong>{{ $tool['description'] }}</span></a>@endforeach
    </nav>

    <section class="customizer-preview" aria-labelledby="customizer-preview-title">
        <div class="customizer-preview__head"><div><h2 id="customizer-preview-title">Website preview</h2><p>Design presets preview immediately. Save when the result looks right.</p></div><div class="customizer-preview__controls" aria-label="Preview controls"><label class="sr-only" for="customizer-preview-page">Page to preview</label><select id="customizer-preview-page" class="preview-page">@foreach($previewPages as $label => $url)<option value="{{ $url }}">{{ $label }}</option>@endforeach</select><button class="preview-device is-active" type="button" data-preview-width="100%" aria-label="Desktop preview" aria-pressed="true"><i class="fa fa-desktop" aria-hidden="true"></i></button><button class="preview-device" type="button" data-preview-width="768px" aria-label="Tablet preview" aria-pressed="false"><i class="fa fa-tablet" aria-hidden="true"></i></button><button class="preview-device" type="button" data-preview-width="390px" aria-label="Mobile preview" aria-pressed="false"><i class="fa fa-mobile" aria-hidden="true"></i></button><button id="refresh-customizer-preview" class="igf-btn igf-btn--quiet" type="button"><i class="fa fa-refresh" aria-hidden="true"></i> Refresh</button></div></div>
        <div class="customizer-preview__stage"><iframe id="customizer-preview-frame" src="{{ route('frontend.home') }}" title="Public website preview"></iframe></div>
    </section>

    <div class="customizer-workspace">
        <aside class="customizer-nav" aria-label="Customizer sections">
            <div class="customizer-nav__search"><label for="customizer-search">Find a setting</label><input id="customizer-search" type="search" placeholder="Try logo, phone, Zakat..."></div>
            @foreach($schema as $groupKey => $group)<a href="#settings-{{ $groupKey }}"><span>{{ $group['label'] }}</span><small>{{ count($group['fields']) }}</small></a>@endforeach
            <form class="customizer-locale" method="GET" action="{{ route('site.settings.index') }}"><label for="settings-locale">Editing language</label><select id="settings-locale" name="locale" onchange="this.form.submit()">@foreach($locales as $option)<option value="{{ $option->id }}" @selected($option->id === $locale)>{{ $option->name }}</option>@endforeach</select></form>
        </aside>

        <section aria-label="Website settings">
            <div id="customizer-no-results" class="customizer-no-results"><h2>No matching settings</h2><p>Try a shorter or more general search.</p></div>
            <form id="customizer-form" method="POST" action="{{ route('site.settings.update') }}">
                @csrf @method('PUT')<input type="hidden" name="locale" value="{{ $locale }}">
                <div class="customizer-groups">
                    @foreach($schema as $groupKey => $group)
                        <details class="customizer-card" id="settings-{{ $groupKey }}" data-settings-group @if($loop->first) open @endif>
                            <summary><div><h2>{{ $group['label'] }}</h2><p>{{ $group['description'] }}</p></div><i class="fa fa-chevron-down" aria-hidden="true"></i></summary>
                            <div class="customizer-fields">
                                @if($groupKey === 'donation_page')
                                    <div class="donation-builder">
                                        <div><strong>No-code donation builder</strong><p>Design and wording are editable below. Required identity fields, server validation and payment verification stay protected so an accidental setting cannot weaken checkout security.</p></div>
                                        <div class="donation-builder__actions">@if($canUse('donationType.index'))<a class="igf-btn" href="{{ route('donationType.index') }}"><i class="fa fa-list" aria-hidden="true"></i> Manage donation causes</a>@endif<a class="igf-btn igf-btn--quiet" href="{{ route('frontend.donate.index') }}" target="_blank" rel="noopener"><i class="fa fa-external-link" aria-hidden="true"></i> Open donation page</a></div>
                                    </div>
                                    <section class="payment-provider-status" aria-labelledby="payment-provider-status-title">
                                        <div class="payment-provider-status__head"><div><strong id="payment-provider-status-title">Payment provider status</strong><p>Read-only checks from the protected payment configuration. The Offer switches below control public visibility; they cannot activate a payment channel.</p></div><span>Read only</span></div>
                                        <ul>
                                            @foreach(($paymentProviderStatuses ?? []) as $provider)
                                                <li @class(['is-ready' => $provider['ready']])><div><strong>{{ $provider['label'] }}</strong><small>{{ $provider['message'] }}</small></div><span><i class="fa {{ $provider['ready'] ? 'fa-check-circle' : 'fa-warning' }}" aria-hidden="true"></i>{{ $provider['status'] }}</span></li>
                                            @endforeach
                                        </ul>
                                    </section>
                                @endif
                                @if($groupKey === 'zakat_calculator')
                                    <div class="donation-builder">
                                        <div><strong>Keep the Nisab trustworthy</strong><p>1. Open the named market source. 2. Enter the current Shariah-approved gold and silver reference prices per gram—not jewellery totals. 3. Record the source and the date you checked it. 4. Save, then preview the Zakat page. The threshold is calculated automatically; the protected 2.5% rate cannot be changed here. Any older fixed Nisab amount is retained only as legacy data and no longer controls the public result.</p></div>
                                        <div class="donation-builder__actions"><a class="igf-btn igf-btn--quiet" href="{{ route('frontend.zakat') }}" target="_blank" rel="noopener"><i class="fa fa-external-link" aria-hidden="true"></i> Open Zakat page</a></div>
                                    </div>
                                @endif
                                @foreach($group['fields'] as $key => $field)
                                    @php($inputName = "settings[$groupKey][$key]") @php($inputId = "setting-$groupKey-$key") @php($value = old("settings.$groupKey.$key", data_get($values, "$groupKey.$key")))
                                    <div class="customizer-field" data-setting-row data-search="{{ strtolower($group['label'].' '.$field['label'].' '.$key) }}">
                                        @if($field['type'] === 'select')
                                            <div id="{{ $inputId }}-label" class="customizer-field__label">{{ $field['label'] }} @if(isset($field['help']))<small>{{ $field['help'] }}</small>@endif @if(!($field['localized'] ?? false))<small>Used in every language</small>@endif</div>
                                        @else
                                            <label for="{{ $inputId }}">{{ $field['label'] }} @if(isset($field['help']))<small>{{ $field['help'] }}</small>@endif @if(!($field['localized'] ?? false))<small>Used in every language</small>@endif</label>
                                        @endif
                                        <div class="customizer-control">
                                            @if(($field['picker'] ?? null) === 'image')
                                                <div class="media-setting"><div class="media-setting__preview"><img id="{{ $inputId }}-preview" src="{{ $value }}" alt="Current {{ strtolower($field['label']) }} preview" onerror="this.style.visibility='hidden'"></div><div class="media-setting__actions">@if($canUpdateSettings)<button class="igf-btn" type="button" data-media-open="{{ $inputId }}"><i class="fa fa-images" aria-hidden="true"></i> Choose image</button>@endif @if($canUse('media.index'))<a class="igf-btn igf-btn--quiet" href="{{ route('media.index', ['type' => 'image']) }}" target="_blank" rel="noopener">Upload images</a>@endif<details class="media-setting__advanced"><summary>Advanced: image address</summary><input id="{{ $inputId }}" name="{{ $inputName }}" type="text" value="{{ $value }}" autocomplete="off" @disabled(!$canUpdateSettings)></details></div></div>
                                            @elseif($field['type'] === 'boolean')
                                                <input type="hidden" name="{{ $inputName }}" value="0" @disabled(!$canUpdateSettings)><label class="customizer-check"><input id="{{ $inputId }}" type="checkbox" name="{{ $inputName }}" value="1" @checked((bool)$value) @disabled(!$canUpdateSettings)> Enabled</label>
                                            @elseif($field['type'] === 'textarea')
                                                <textarea id="{{ $inputId }}" name="{{ $inputName }}" @disabled(!$canUpdateSettings)>{{ $value }}</textarea>
                                            @elseif($field['type'] === 'select')
                                                <fieldset class="customizer-presets" aria-labelledby="{{ $inputId }}-label">
                                                    @foreach($field['options'] as $optionValue => $optionLabel)
                                                        <label class="customizer-preset"><input id="{{ $inputId }}-{{ $optionValue }}" type="radio" name="{{ $inputName }}" value="{{ $optionValue }}" @checked((string)$value === (string)$optionValue) @disabled(!$canUpdateSettings)><span>{{ $optionLabel }}</span></label>
                                                    @endforeach
                                                </fieldset>
                                            @else
                                                <input id="{{ $inputId }}" name="{{ $inputName }}" type="{{ match($field['type']) { 'integer', 'float' => 'number', 'email', 'color', 'date', 'url' => $field['type'], default => 'text' } }}" @if(in_array($field['type'], ['integer', 'float'], true)) min="{{ $field['min'] ?? ($field['type'] === 'integer' ? 1 : 0.01) }}" max="{{ $field['max'] ?? 10000000 }}" step="{{ $field['type'] === 'integer' ? 1 : ($field['step'] ?? '0.01') }}" @endif @if($field['type'] === 'date') max="{{ now()->toDateString() }}" @endif value="{{ $value }}" @disabled(!$canUpdateSettings)>
                                            @endif
                                            @error("settings.$groupKey.$key")<small class="text-danger">{{ $message }}</small>@enderror
                                        </div>
                                        @if($canResetSettings)<button class="customizer-reset" type="submit" form="reset-{{ $groupKey }}-{{ $key }}">Reset to default</button>@endif
                                    </div>
                                @endforeach
                            </div>
                        </details>
                    @endforeach
                </div>
                @if($canUpdateSettings)<div class="customizer-save"><span id="customizer-status-bottom" class="customizer-status" role="status">Unsaved changes</span><button class="igf-btn igf-btn--primary" type="submit"><i class="fa fa-save" aria-hidden="true"></i> Save website changes</button></div>@endif
            </form>
        </section>
    </div>

    @if($canResetSettings) @foreach($schema as $groupKey => $group) @foreach($group['fields'] as $key => $field)<form id="reset-{{ $groupKey }}-{{ $key }}" method="POST" action="{{ route('site.settings.destroy', [$groupKey, $key]) }}" onsubmit="return confirm('Reset this setting to its original value?')">@csrf @method('DELETE')<input type="hidden" name="locale" value="{{ $locale }}"></form>@endforeach @endforeach @endif
</main>

@if($canUpdateSettings)<div id="media-picker" class="media-modal" role="dialog" aria-modal="true" aria-labelledby="media-picker-title" hidden>
    <div class="media-modal__dialog"><div class="media-modal__head"><h2 id="media-picker-title">Choose an image</h2><button class="media-modal__close" type="button" data-media-close aria-label="Close image picker"><i class="fa fa-times" aria-hidden="true"></i></button></div><div class="media-modal__search"><label class="sr-only" for="media-picker-search">Search images</label><input id="media-picker-search" type="search" placeholder="Search uploaded images"></div><div class="media-modal__grid" id="media-picker-grid">@forelse($mediaAssets as $asset)<button class="media-choice" type="button" data-media-url="{{ $asset->url }}" data-media-name="{{ strtolower($asset->original_name.' '.$asset->alt_text) }}"><img src="{{ $asset->url }}" alt="{{ $asset->alt_text ?: $asset->original_name }}"><span>{{ $asset->original_name }}</span></button>@empty<div class="media-empty"><p>No images have been uploaded to the Media Library yet.</p>@if($canUse('media.index'))<a class="igf-btn igf-btn--primary" href="{{ route('media.index', ['type' => 'image']) }}">Open Media Library</a>@endif</div>@endforelse</div></div>
</div>@endif
@endsection

@section('custom-js')
<script>
(() => {
    const form = document.getElementById('customizer-form'); const status = document.getElementById('customizer-status'); const statusBottom = document.getElementById('customizer-status-bottom'); const frame = document.getElementById('customizer-preview-frame'); const modal = document.getElementById('media-picker'); const mediaSearch = document.getElementById('media-picker-search'); let dirty = false; let activeMediaInput = null;
    const designPreviewMaps = {
        content_width:{compact:{'--igf-content-width':'1040px'},standard:{'--igf-content-width':'1240px'},wide:{'--igf-content-width':'1400px'}},
        heading_size:{compact:{'--igf-heading-1':'clamp(38px,5vw,64px)','--igf-heading-2':'clamp(30px,3.6vw,44px)','--igf-heading-3':'20px','--igf-heading-1-mobile':'36px','--igf-heading-2-mobile':'30px'},standard:{'--igf-heading-1':'clamp(42px,6vw,76px)','--igf-heading-2':'clamp(34px,4vw,52px)','--igf-heading-3':'22px','--igf-heading-1-mobile':'42px','--igf-heading-2-mobile':'34px'},large:{'--igf-heading-1':'clamp(48px,7vw,88px)','--igf-heading-2':'clamp(38px,5vw,62px)','--igf-heading-3':'25px','--igf-heading-1-mobile':'48px','--igf-heading-2-mobile':'38px'}},
        body_text_size:{compact:{'--igf-body-size':'15px','--igf-lead-size':'clamp(17px,1.8vw,19px)','--igf-testimonial-text-size':'clamp(20px,2.5vw,28px)'},standard:{'--igf-body-size':'17px','--igf-lead-size':'clamp(18px,2vw,21px)','--igf-testimonial-text-size':'clamp(22px,3vw,33px)'},large:{'--igf-body-size':'19px','--igf-lead-size':'clamp(20px,2.2vw,24px)','--igf-testimonial-text-size':'clamp(26px,3.4vw,38px)'}},
        section_spacing:{compact:{'--igf-section-block':'clamp(56px,7vw,88px)','--igf-section-mobile':'52px'},standard:{'--igf-section-block':'clamp(72px,9vw,120px)','--igf-section-mobile':'68px'},generous:{'--igf-section-block':'clamp(88px,11vw,144px)','--igf-section-mobile':'82px'}},
        hero_height:{compact:{'--igf-hero-height':'min(650px,78vh)','--igf-hero-height-mobile':'580px'},standard:{'--igf-hero-height':'min(780px,86vh)','--igf-hero-height-mobile':'680px'},tall:{'--igf-hero-height':'min(900px,92vh)','--igf-hero-height-mobile':'780px'}},
        image_size:{compact:{'--igf-card-media-height':'170px'},standard:{'--igf-card-media-height':'230px'},large:{'--igf-card-media-height':'310px'}},
        image_shape:{square:{'--igf-image-aspect':'1 / 1'},portrait:{'--igf-image-aspect':'4 / 5'},landscape:{'--igf-image-aspect':'4 / 3'},wide:{'--igf-image-aspect':'16 / 9'}},
        card_columns:{2:{'--igf-card-columns':'2'},3:{'--igf-card-columns':'3'},4:{'--igf-card-columns':'4'}},
        card_style:{soft:{'--igf-card-border':'#e5e0dc','--igf-card-radius':'16px','--igf-card-shadow':'0 5px 18px rgba(25,28,29,.05)'},outlined:{'--igf-card-border':'#9f9389','--igf-card-radius':'10px','--igf-card-shadow':'none'},elevated:{'--igf-card-border':'transparent','--igf-card-radius':'20px','--igf-card-shadow':'0 16px 36px rgba(25,28,29,.14)'}},
        button_shape:{square:{'--igf-button-radius':'4px'},rounded:{'--igf-button-radius':'10px'},pill:{'--igf-button-radius':'999px'}},
        logo_size:{compact:{'--igf-brand-font-size':'17px','--igf-brand-mark-width':'32px','--igf-brand-mark-size':'27px'},standard:{'--igf-brand-font-size':'20px','--igf-brand-mark-width':'38px','--igf-brand-mark-size':'32px'},large:{'--igf-brand-font-size':'23px','--igf-brand-mark-width':'44px','--igf-brand-mark-size':'38px'}}
    };
    function applyDesignPreview(){try{const root=frame?.contentDocument?.querySelector('[style*="--igf-primary"]');if(!root)return;Object.entries(designPreviewMaps).forEach(([field,presets])=>{const selected=form?.querySelector(`[name="settings[design][${field}]"]:checked`);const variables=presets[selected?.value];if(!variables)return;Object.entries(variables).forEach(([property,value])=>root.style.setProperty(property,value))})}catch(error){/* The preview may still be loading. */}}
    function openHashGroup(){const group=document.querySelector(window.location.hash);if(group?.matches('[data-settings-group]')){group.open=true;group.scrollIntoView({block:'start'})}}
    function setDirty(value = true){dirty=value;status?.classList.toggle('is-visible',value);statusBottom?.classList.toggle('is-visible',value)}
    form?.querySelectorAll('input:not([type=hidden]),textarea,select').forEach(control=>control.addEventListener(control.matches('select,input[type=checkbox],input[type=color],input[type=radio]')?'change':'input',()=>setDirty(true))); form?.addEventListener('input',event=>{if(event.target?.name?.startsWith('settings[design]'))applyDesignPreview()}); form?.addEventListener('change',event=>{if(event.target?.name?.startsWith('settings[design]'))applyDesignPreview()}); form?.addEventListener('submit',()=>setDirty(false)); window.addEventListener('beforeunload',event=>{if(!dirty)return;event.preventDefault();event.returnValue=''})
    frame?.addEventListener('load',applyDesignPreview); document.getElementById('customizer-preview-page')?.addEventListener('change',event=>{frame.src=event.target.value}); document.querySelectorAll('[data-preview-width]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-preview-width]').forEach(item=>{const active=item===button;item.classList.toggle('is-active',active);item.setAttribute('aria-pressed',String(active))});frame.style.width=button.dataset.previewWidth})); document.getElementById('refresh-customizer-preview')?.addEventListener('click',()=>{const url=new URL(frame.src);url.searchParams.set('preview',String(Date.now()));frame.src=url.toString()});
    const settingRows=[...document.querySelectorAll('[data-setting-row]')]; const settingGroups=[...document.querySelectorAll('[data-settings-group]')]; const noResults=document.getElementById('customizer-no-results'); document.getElementById('customizer-search')?.addEventListener('input',event=>{const query=event.target.value.trim().toLowerCase();let visibleCount=0;settingRows.forEach(row=>{const visible=!query||row.dataset.search.includes(query);row.hidden=!visible;if(visible)visibleCount+=1});settingGroups.forEach(group=>{const visible=[...group.querySelectorAll('[data-setting-row]')].some(row=>!row.hidden);group.hidden=!visible;if(query&&visible)group.open=true});noResults?.classList.toggle('is-visible',visibleCount===0)});
    function closeMediaPicker(){if(!modal)return;modal.hidden=true;activeMediaInput=null} document.querySelectorAll('[data-media-open]').forEach(button=>button.addEventListener('click',()=>{activeMediaInput=document.getElementById(button.dataset.mediaOpen);modal.hidden=false;mediaSearch.value='';document.querySelectorAll('.media-choice').forEach(choice=>{choice.hidden=false});window.setTimeout(()=>mediaSearch.focus(),20)})); document.querySelectorAll('[data-media-close]').forEach(button=>button.addEventListener('click',closeMediaPicker)); modal?.addEventListener('click',event=>{if(event.target===modal)closeMediaPicker()}); document.addEventListener('keydown',event=>{if(event.key==='Escape'&&modal&&!modal.hidden)closeMediaPicker()}); mediaSearch?.addEventListener('input',()=>{const query=mediaSearch.value.trim().toLowerCase();document.querySelectorAll('.media-choice').forEach(choice=>{choice.hidden=Boolean(query)&&!choice.dataset.mediaName.includes(query)})}); document.querySelectorAll('.media-choice').forEach(choice=>choice.addEventListener('click',()=>{if(!activeMediaInput)return;activeMediaInput.value=choice.dataset.mediaUrl;activeMediaInput.dispatchEvent(new Event('input',{bubbles:true}));const preview=document.getElementById(activeMediaInput.id+'-preview');if(preview){preview.src=choice.dataset.mediaUrl;preview.style.visibility='visible'}closeMediaPicker()})); window.addEventListener('hashchange',openHashGroup); openHashGroup();
})();
</script>
@endsection
