@extends('admin.layouts.master')

@section('content')
<style>
    .igf-customizer{--orange:#f26322;--brown:#8c3d0a;--ink:#25282a;--muted:#6d6d69;--line:#e7e2dc;max-width:1380px;margin:0 auto;padding:30px 24px 70px;color:var(--ink);font-family:'Hanken Grotesk',Arial,sans-serif}.igf-customizer *{box-sizing:border-box}
    .customizer-head{display:flex;align-items:flex-start;justify-content:space-between;gap:24px;margin-bottom:14px}.customizer-head h1{margin:0;font:700 clamp(38px,4vw,58px)/1.05 'Literata',Georgia,serif;letter-spacing:-.035em}.customizer-head p{max-width:720px;margin:9px 0 0;color:var(--muted);font-size:15px;line-height:1.6}.customizer-head__actions{display:flex;align-items:center;gap:10px}.customizer-status{display:none;color:#79500f;font-size:12px;font-weight:800}.customizer-status.is-visible{display:inline}.customizer-status.is-success{color:#27713c}.customizer-status.is-error{color:#9c3029}.igf-btn{display:inline-flex;min-width:44px;min-height:44px;align-items:center;justify-content:center;gap:8px;border:1px solid #d9d2ca;border-radius:8px;padding:8px 16px;background:#fff;color:#4a4540;font-size:13px;font-weight:800;text-decoration:none;cursor:pointer}.igf-btn:hover{border-color:var(--orange);color:var(--brown)}.igf-btn--primary{border-color:var(--brown);background:var(--brown);color:#fff}.igf-btn--primary:hover{border-color:#6f2f07;background:#6f2f07;color:#fff}.igf-btn--primary:disabled{cursor:not-allowed;opacity:.52}.igf-btn--quiet{background:#f7f4f1}.igf-btn:focus-visible{outline:3px solid var(--brown);outline-offset:2px}
    .customizer-tools{display:grid;grid-template-columns:repeat(auto-fit,minmax(145px,1fr));gap:11px;margin-bottom:22px}.customizer-tool{display:grid;min-height:118px;align-content:space-between;gap:14px;border:1px solid var(--line);border-radius:12px;padding:16px;background:#fff;color:var(--ink);text-decoration:none;box-shadow:0 7px 22px rgba(37,40,42,.035);transition:.18s}.customizer-tool:hover{transform:translateY(-2px);border-color:#efb68c;box-shadow:0 11px 25px rgba(37,40,42,.07)}.customizer-tool i{color:var(--orange);font-size:23px}.customizer-tool strong{display:block;margin-bottom:3px;font:650 15px 'Literata',Georgia,serif}.customizer-tool span{color:var(--muted);font-size:11px;line-height:1.45}
    .customizer-guide{margin:-8px 0 20px;border:1px solid #f0c5a5;border-radius:11px;background:#fff8f2}.customizer-guide summary{padding:14px 17px;color:var(--brown);font-size:13px;font-weight:850;cursor:pointer}.customizer-guide ol{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px;margin:0;padding:0 17px 17px;counter-reset:steps;list-style:none}.customizer-guide li{position:relative;padding:11px 11px 11px 38px;border-radius:8px;background:#fff;color:#5f5953;font-size:11px;line-height:1.45}.customizer-guide li::before{position:absolute;top:10px;left:10px;display:grid;width:20px;height:20px;place-content:center;border-radius:50%;background:var(--orange);color:#fff;content:counter(steps);counter-increment:steps;font-size:10px;font-weight:900}.customizer-guide strong{display:block;color:var(--ink)}
    .customizer-preview{margin-bottom:24px;border:1px solid var(--line);border-radius:14px;background:#fff;box-shadow:0 8px 26px rgba(37,40,42,.045)}.customizer-preview__head{display:flex;align-items:center;justify-content:space-between;gap:18px;padding:15px 18px;border-bottom:1px solid var(--line)}.customizer-preview__head h2{margin:0;font:650 20px 'Literata',Georgia,serif}.customizer-preview__head p{margin:4px 0 0;color:var(--muted);font-size:12px}.customizer-preview__controls{display:flex;align-items:center;gap:7px}.preview-page{height:44px;max-width:190px;border:1px solid #ded8d1;border-radius:7px;padding:0 30px 0 10px;background:#fff;color:#4d4844;font-size:12px;font-weight:750}.preview-device{display:grid;width:44px;height:44px;place-content:center;border:1px solid #ded8d1;border-radius:7px;background:#fff;color:#69625c;cursor:pointer}.preview-device.is-active{border-color:var(--orange);background:#fff2e8;color:var(--brown)}.preview-device:focus-visible{outline:3px solid var(--brown);outline-offset:2px}.customizer-preview__stage{display:flex;min-height:390px;justify-content:center;overflow:auto;padding:18px;background:#eeeae6}.customizer-preview iframe{width:100%;height:370px;border:1px solid #cac4bd;border-radius:7px;background:#fff;box-shadow:0 7px 22px rgba(0,0,0,.08);transition:width .2s ease}
    .customizer-workspace{display:grid;grid-template-columns:230px minmax(0,1fr);align-items:start;gap:22px}.customizer-nav{position:sticky;top:18px;display:grid;gap:5px}.customizer-nav__search{margin-bottom:7px}.customizer-nav__search label{display:block;margin-bottom:6px;font-size:11px;font-weight:800;letter-spacing:.05em;text-transform:uppercase}.customizer-nav__search input{width:100%;height:44px;border:1px solid #d7d1ca;border-radius:8px;padding:8px 11px}.customizer-nav a{display:flex;min-height:44px;align-items:center;justify-content:space-between;gap:8px;border-radius:7px;padding:10px 12px;color:#4b4b47;text-decoration:none}.customizer-nav a:hover{background:#fff2ea;color:var(--brown)}.customizer-nav small{display:grid;min-width:22px;height:22px;place-content:center;border-radius:999px;background:#ece8e4;color:#726c66;font-size:10px}.customizer-locale{margin-top:10px;padding:14px;border:1px solid var(--line);border-radius:10px;background:#fff}.customizer-locale label{display:block;margin-bottom:6px;font-size:11px;font-weight:800;text-transform:uppercase}.customizer-locale select{width:100%;height:44px;border:1px solid #d7d1ca;border-radius:7px;padding:8px;background:#fff}
    .customizer-groups{display:grid;gap:14px}.customizer-card{border:1px solid var(--line);border-radius:12px;background:#fff;box-shadow:0 7px 22px rgba(37,40,42,.035)}.customizer-card[hidden]{display:none}.customizer-card>summary{display:grid;grid-template-columns:1fr auto;align-items:center;gap:18px;padding:19px 21px;cursor:pointer;list-style:none}.customizer-card>summary::-webkit-details-marker{display:none}.customizer-card>summary h2{margin:0;font:650 23px 'Literata',Georgia,serif}.customizer-card>summary p{margin:5px 0 0;color:var(--muted);font-size:13px}.customizer-card>summary i{color:var(--orange);transition:transform .18s}.customizer-card[open]>summary i{transform:rotate(180deg)}.customizer-fields{border-top:1px solid var(--line);padding:4px 21px}.donation-builder{display:grid;grid-template-columns:1fr auto;align-items:center;gap:18px;margin:0 -21px;padding:18px 21px;border-bottom:1px solid #eadfd6;background:#fff8f2}.donation-builder strong{display:block;margin-bottom:4px;color:var(--brown);font-size:14px}.donation-builder p{margin:0;color:#6e625b;font-size:11px;line-height:1.5}.donation-builder__actions{display:flex;flex-wrap:wrap;gap:8px}.customizer-field{display:grid;grid-template-columns:minmax(170px,.75fr) minmax(280px,1.5fr) auto;align-items:start;gap:18px;padding:17px 0;border-bottom:1px solid #f1eee9}.customizer-field:last-child{border:0}.customizer-field>label,.customizer-field__label{padding-top:10px;font-weight:750}.customizer-field>label small,.customizer-field__label small{display:block;margin-top:5px;color:#8a837c;font-size:10px;font-weight:600;line-height:1.45}.customizer-control input:not([type=checkbox],[type=radio]),.customizer-control textarea{width:100%;min-height:44px;border:1px solid #d7d1ca;border-radius:7px;padding:10px 11px;background:#fff;color:var(--ink)}.customizer-control textarea{min-height:90px;resize:vertical}.customizer-control input[type=color]{height:46px;padding:4px}.customizer-control input:focus,.customizer-control textarea:focus{outline:3px solid rgba(242,99,34,.16);border-color:var(--orange)}.customizer-check{display:flex;min-height:44px;align-items:center;gap:9px;margin:0}.customizer-check input{width:19px;height:19px;accent-color:var(--orange)}.customizer-reset{margin-top:8px;border:0;background:transparent;color:var(--brown);font-size:11px;font-weight:750;cursor:pointer}.customizer-reset:hover{text-decoration:underline}.customizer-no-results{display:none;padding:50px;border:1px dashed #d7d1ca;border-radius:12px;background:#fff;text-align:center}.customizer-no-results.is-visible{display:block}
    .customizer-presets{display:grid;grid-template-columns:repeat(auto-fit,minmax(112px,1fr));gap:8px;margin:0;padding:0;border:0}.customizer-preset{position:relative;margin:0;cursor:pointer}.customizer-preset input{position:absolute;width:1px;height:1px;opacity:0;pointer-events:none}.customizer-preset span{display:grid;min-height:58px;place-content:center;border:1px solid #d7d1ca;border-radius:9px;padding:10px;background:#faf9f7;color:#5f5953;font-size:12px;font-weight:800;text-align:center;transition:.15s ease}.customizer-preset:hover span{border-color:#efb68c;background:#fff7f1}.customizer-preset input:checked+span{border-color:var(--orange);background:#fff0e4;color:var(--brown);box-shadow:inset 0 0 0 1px var(--orange)}.customizer-preset input:focus-visible+span{outline:3px solid var(--brown);outline-offset:2px}
    .media-setting{display:grid;grid-template-columns:112px minmax(0,1fr);gap:14px}.media-setting__preview{display:grid;width:112px;height:84px;overflow:hidden;place-content:center;border:1px solid #ded8d2;border-radius:9px;background:#f1efec}.media-setting__preview img{width:112px;height:84px;object-fit:cover}.media-setting__actions{display:flex;flex-wrap:wrap;align-content:center;gap:8px}.media-setting__advanced{width:100%}.media-setting__advanced summary{display:inline-flex;min-height:44px;align-items:center;color:#756e68;font-size:11px;cursor:pointer}.media-setting__advanced input{margin-top:8px;font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:11px}.customizer-save{position:sticky;z-index:50;top:73px;display:flex;align-items:center;justify-content:flex-end;gap:12px;margin:0 0 18px;padding:10px 12px;border:1px solid var(--line);border-radius:10px;background:rgba(245,245,243,.96);box-shadow:0 7px 20px rgba(37,40,42,.08);backdrop-filter:blur(8px)}
    .media-modal[hidden]{display:none}.media-modal{position:fixed;z-index:10000;inset:0;display:grid;place-items:center;padding:22px;background:rgba(25,28,29,.62)}.media-modal__dialog{display:grid;width:min(940px,100%);max-height:min(760px,92vh);grid-template-rows:auto auto minmax(0,1fr);overflow:hidden;border-radius:15px;background:#fff;box-shadow:0 24px 70px rgba(0,0,0,.28)}.media-modal__head{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:19px 21px;border-bottom:1px solid var(--line)}.media-modal__head h2{margin:0;font:650 25px 'Literata',Georgia,serif}.media-modal__close{display:grid;width:44px;height:44px;place-content:center;border:0;border-radius:8px;background:#f2efec;cursor:pointer}.media-modal__close:focus-visible{outline:3px solid var(--brown);outline-offset:2px}.media-modal__search{padding:14px 20px;border-bottom:1px solid var(--line)}.media-modal__search input{width:100%;height:44px;border:1px solid #d7d1ca;border-radius:8px;padding:9px 12px}.media-modal__grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));align-content:start;gap:12px;overflow:auto;padding:18px 20px 24px}.media-choice{min-height:44px;overflow:hidden;border:1px solid var(--line);border-radius:10px;background:#fff;text-align:left;cursor:pointer}.media-choice:hover,.media-choice:focus-visible{border-color:var(--orange);outline:3px solid var(--brown);outline-offset:2px}.media-choice img{display:block;width:100%;aspect-ratio:4/3;object-fit:cover;background:#eee}.media-choice span{display:block;overflow:hidden;padding:10px;color:#4d4844;font-size:11px;font-weight:700;text-overflow:ellipsis;white-space:nowrap}.media-empty{grid-column:1/-1;padding:48px;text-align:center;color:var(--muted)}
    .customizer-read-only{margin:0 0 22px;padding:14px 17px;border:1px solid #edcf9f;border-radius:10px;background:#fff8e8;color:#74501d;font-size:13px;line-height:1.55}.customizer-read-only strong{display:block;margin-bottom:2px;color:#56370d}.customizer-control :disabled{cursor:not-allowed;opacity:.72}
    .customizer-validation{margin:0 0 18px;padding:15px 17px;border:1px solid #e3aaa5;border-left:5px solid #a52c24;border-radius:10px;background:#fff3f1;color:#74251f}.customizer-validation[hidden]{display:none}.customizer-validation strong{display:block;margin-bottom:6px}.customizer-validation p{margin:0 0 8px}.customizer-validation ul{margin:0;padding-left:20px}.customizer-validation a{color:#74251f;font-weight:800}
    .payment-provider-status{margin:0 -21px;padding:18px 21px;border-bottom:1px solid #eadfd6;background:#fbfaf8}.payment-provider-status__head{display:flex;align-items:start;justify-content:space-between;gap:18px;margin-bottom:12px}.payment-provider-status__head strong{display:block;color:var(--ink);font-size:14px}.payment-provider-status__head p{max-width:700px;margin:4px 0 0;color:var(--muted);font-size:11px;line-height:1.5}.payment-provider-status__head span{border-radius:999px;padding:4px 9px;background:#ece8e4;color:#645e58;font-size:9px;font-weight:850;letter-spacing:.04em;text-transform:uppercase}.payment-provider-status ul{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px;margin:0;padding:0;list-style:none}.payment-provider-status li{display:grid;grid-template-columns:1fr auto;align-items:start;gap:9px;border:1px solid #e2ddd7;border-radius:9px;padding:12px;background:#fff}.payment-provider-status li>div>strong{display:block;color:var(--ink);font-size:13px}.payment-provider-status li small{display:block;margin-top:4px;color:#766f69;font-size:10px;line-height:1.45}.payment-provider-status li>span{display:inline-flex;align-items:center;gap:5px;border-radius:999px;padding:4px 7px;background:#f4ece6;color:#8a3f13;font-size:9px;font-weight:850;white-space:nowrap}.payment-provider-status li.is-ready>span{background:#e8f5ec;color:#27713c}
    @media(max-width:1150px){.customizer-tools{grid-template-columns:repeat(3,1fr)}}
    @media(max-width:1100px){.igf-customizer{padding-inline:14px}.customizer-head{flex-direction:column}.customizer-head__actions{width:100%;flex-wrap:wrap}.customizer-guide ol{grid-template-columns:1fr 1fr}.customizer-workspace{grid-template-columns:1fr}.customizer-nav{position:static;grid-template-columns:repeat(2,minmax(0,1fr))}.customizer-nav__search,.customizer-locale{grid-column:1/-1}.customizer-field{grid-template-columns:1fr}.customizer-field>label{padding-top:0}.customizer-reset{justify-self:start}.customizer-preview__head{align-items:flex-start;flex-direction:column}.donation-builder{grid-template-columns:1fr}.payment-provider-status ul{grid-template-columns:1fr}}
    @media(max-width:560px){.customizer-guide ol{grid-template-columns:1fr}.customizer-tools{grid-template-columns:repeat(2,1fr)}.customizer-tool{min-height:105px}.customizer-nav{grid-template-columns:1fr}.customizer-nav__search,.customizer-locale{grid-column:auto}.media-setting{grid-template-columns:84px minmax(0,1fr)}.media-setting__preview,.media-setting__preview img{width:84px;height:70px}.customizer-preview__controls{flex-wrap:wrap}.customizer-preview__stage{padding:9px}.media-modal{padding:9px}.media-modal__grid{grid-template-columns:repeat(2,minmax(0,1fr));padding-inline:12px}}
</style>

<style>
    .customizer-faq-editor{padding:18px 0;border-bottom:1px solid #f1eee9}.customizer-faq-editor__head{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:13px}.customizer-faq-editor__head h3{margin:0;font:650 18px 'Literata',Georgia,serif}.customizer-faq-editor__head p{margin:4px 0 0;color:var(--muted);font-size:11px;line-height:1.5}.customizer-faq-editor__actions,.customizer-faq-item__actions{display:flex;flex-wrap:wrap;gap:7px}.customizer-faq-count{display:inline-flex;align-items:center;border-radius:999px;padding:5px 9px;background:#f1ece8;color:#685f59;font-size:10px;font-weight:850}.customizer-faq-list{display:grid;gap:12px}.customizer-faq-item{border:1px solid #e3ddd7;border-radius:11px;padding:15px;background:#fbfaf8}.customizer-faq-item__head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:12px}.customizer-faq-item__head strong{color:var(--brown);font-size:12px}.customizer-faq-item__actions button{min-width:44px;min-height:44px;border:1px solid #ddd5ce;border-radius:7px;background:#fff;color:#5d5650;cursor:pointer}.customizer-faq-item__actions button:hover{border-color:var(--orange);color:var(--brown)}.customizer-faq-item__actions button:disabled{cursor:not-allowed;opacity:.4}.customizer-faq-item__actions .is-danger{color:#9c3029}.customizer-faq-fields{display:grid;grid-template-columns:minmax(220px,.8fr) minmax(300px,1.2fr);gap:12px}.customizer-faq-field{display:grid;gap:6px}.customizer-faq-field label{font-size:11px;font-weight:850}.customizer-faq-field input,.customizer-faq-field textarea{width:100%;min-height:44px;border:1px solid #d7d1ca;border-radius:7px;padding:10px 11px;background:#fff;color:var(--ink)}.customizer-faq-field textarea{min-height:92px;resize:vertical}.customizer-faq-field input:focus,.customizer-faq-field textarea:focus{outline:3px solid rgba(242,99,34,.16);border-color:var(--orange)}.customizer-faq-item__visibility{grid-column:1/-1}.customizer-faq-empty{margin:0;padding:24px;border:1px dashed #d7d1ca;border-radius:9px;color:var(--muted);text-align:center}.customizer-faq-error{display:block;margin:10px 0 0;color:#b42318;font-size:11px;font-weight:750}
    .customizer-form-layout{padding:18px 0;border-bottom:1px solid #f1eee9}.customizer-form-layout__head{margin-bottom:13px}.customizer-form-layout__head h3{margin:0;font:650 18px 'Literata',Georgia,serif}.customizer-form-layout__head p{max-width:760px;margin:5px 0 0;color:var(--muted);font-size:11px;line-height:1.5}.customizer-form-layout__list{display:grid;gap:9px}.customizer-form-layout__item{display:grid;grid-template-columns:minmax(190px,1fr) auto auto;align-items:center;gap:14px;border:1px solid #e3ddd7;border-radius:10px;padding:12px 14px;background:#fbfaf8}.customizer-form-layout__identity{display:flex;align-items:center;gap:10px;min-width:0}.customizer-form-layout__identity>span{display:grid;min-width:30px;height:30px;place-content:center;border-radius:50%;background:#f2e5db;color:var(--brown);font-size:10px;font-weight:900}.customizer-form-layout__identity strong{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.customizer-form-layout__identity small{display:block;margin-top:2px;color:var(--muted);font-size:9px;font-weight:750}.customizer-form-layout__options{display:flex;align-items:center;gap:16px}.customizer-form-layout__options .customizer-check{font-size:11px;font-weight:750}.customizer-form-layout__actions{display:flex;gap:6px}.customizer-form-layout__actions button{display:grid;min-width:44px;height:44px;place-content:center;border:1px solid #d9d2ca;border-radius:7px;background:#fff;color:#5d5650;cursor:pointer}.customizer-form-layout__actions button:hover{border-color:var(--orange);color:var(--brown)}.customizer-form-layout__actions button:disabled{cursor:not-allowed;opacity:.4}
    @media(max-width:1100px){.customizer-faq-fields{grid-template-columns:1fr}.customizer-form-layout__item{grid-template-columns:1fr auto}.customizer-form-layout__actions{grid-column:2;grid-row:1/3}.customizer-form-layout__options{grid-column:1}}
    @media(max-width:560px){.customizer-faq-editor__head,.customizer-faq-item__head{align-items:flex-start;flex-direction:column}.customizer-faq-editor__actions{width:100%}.customizer-faq-editor__actions .igf-btn{flex:1}.customizer-form-layout__item{grid-template-columns:1fr}.customizer-form-layout__options{grid-column:1;align-items:flex-start;flex-direction:column;gap:2px}.customizer-form-layout__actions{grid-column:1;grid-row:auto}}
</style>

@php
    $admin = auth('admin')->user();
    $permissions = app(\App\Http\Middleware\Permission::class);
    $canUse = fn (string $route): bool => $permissions->allows($admin, $route);
    $canUpdateSettings = $canUse('site.settings.update');
    $canResetSettings = $canUse('site.settings.destroy');
    $isSettingsViewOnly = !$canUpdateSettings && !$canResetSettings;
    $ui = fn (string $key, array $replace = []): string => \App\Support\AdminUi::text('customizer.'.$key, $replace);
    $toolCards = [
        ['route' => 'page.index', 'label' => $ui('tools.content_hub'), 'description' => $ui('tools.content_hub_help'), 'icon' => 'fa-file-text-o', 'url' => route('page.index')],
        ['route' => 'site.settings.index', 'label' => $ui('tools.design'), 'description' => $ui('tools.design_help'), 'icon' => 'fa-paint-brush', 'url' => route('site.settings.index', ['locale' => $locale]).'#settings-design'],
        ['route' => 'site.settings.index', 'label' => $ui('tools.donation'), 'description' => $ui('tools.donation_help'), 'icon' => 'fa-heart-o', 'url' => route('site.settings.index', ['locale' => $locale]).'#settings-donation_page'],
        ['route' => 'page.menu.index', 'label' => $ui('tools.navigation'), 'description' => $ui('tools.navigation_help'), 'icon' => 'fa-sitemap', 'url' => route('page.menu.index')],
        ['route' => 'media.index', 'label' => $ui('tools.media'), 'description' => $ui('tools.media_help'), 'icon' => 'fa-picture-o', 'url' => route('media.index')],
        ['route' => 'reusable-blocks.index', 'label' => $ui('tools.reusable'), 'description' => $ui('tools.reusable_help'), 'icon' => 'fa-clone', 'url' => route('reusable-blocks.index')],
        ['route' => 'seo.index', 'label' => $ui('tools.search'), 'description' => $ui('tools.search_help'), 'icon' => 'fa-search', 'url' => route('seo.index')],
        ['route' => 'content.trash.index', 'label' => $ui('tools.trash'), 'description' => $ui('tools.trash_help'), 'icon' => 'fa-trash', 'url' => route('content.trash.index')],
    ];
    $toolCards = array_values(array_filter($toolCards, fn (array $tool): bool => $canUse($tool['route'])));
    $previewPages = [
        $ui('preview_pages.home') => route('frontend.home', ['lang' => $locale]),
        $ui('preview_pages.contact') => route('frontend.contactUs', ['lang' => $locale]),
        $ui('preview_pages.donate') => route('frontend.donate.index', ['lang' => $locale]),
        $ui('preview_pages.sponsor') => route('frontend.sponsor_child', ['lang' => $locale]),
        $ui('preview_pages.volunteer') => route('frontend.volunteer_registration.index', ['lang' => $locale]),
        $ui('preview_pages.zakat') => route('frontend.zakat', ['lang' => $locale]),
        $ui('preview_pages.gallery') => route('frontend.gallery', ['lang' => $locale]),
        $ui('preview_pages.reports') => route('frontend.annual_report.index', ['lang' => $locale]),
        $ui('preview_pages.search') => route('search', ['lang' => $locale]),
        $ui('preview_pages.member_login') => route('showLogin', ['lang' => $locale]),
    ];
@endphp

<main class="igf-customizer">
    <header class="customizer-head">
        <div><h1>{{ $ui('title') }}</h1><p>{{ $ui('intro') }}</p></div>
        <div class="customizer-head__actions"><a class="igf-btn" href="{{ route('frontend.home') }}" target="_blank" rel="noopener"><i class="fa fa-external-link" aria-hidden="true"></i> {{ $ui('open_website') }}</a></div>
    </header>

    @if($canUpdateSettings)
        <div class="customizer-save" aria-label="{{ $ui('save_controls') }}">
            <span id="customizer-status" class="customizer-status" role="status" aria-live="polite">{{ $ui('unsaved_changes') }}</span>
            <button id="customizer-save" class="igf-btn igf-btn--primary" type="submit" form="customizer-form" disabled><i class="fa fa-save" aria-hidden="true"></i> {{ $ui('save_changes') }}</button>
        </div>
    @endif

    @if($errors->any())
        <div class="customizer-validation" role="alert" aria-live="assertive">
            <strong>{{ $ui('validation_title') }}</strong>
            <p>{{ $ui('validation_help') }}</p>
            <ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul>
        </div>
    @endif
    @if($canUpdateSettings)
        <div id="customizer-client-validation" class="customizer-validation" role="alert" aria-live="assertive" tabindex="-1" hidden>
            <strong>{{ $ui('validation_title') }}</strong>
            <p>{{ $ui('validation_help') }}</p>
            <ul data-customizer-errors></ul>
        </div>
    @endif

    @if($isSettingsViewOnly)
        <div class="customizer-read-only" role="status"><strong>{{ $ui('read_only_title') }}</strong>{{ $ui('read_only_help') }}</div>
    @elseif(!$canUpdateSettings)
        <div class="customizer-read-only" role="status"><strong>{{ $ui('limited_title') }}</strong>{{ $ui('limited_help') }}</div>
    @endif

    <details class="customizer-guide"><summary><i class="fa fa-question-circle" aria-hidden="true"></i> {{ $ui('guide.title') }}</summary><ol>@foreach(range(1, 5) as $step)<li><strong>{{ $ui("guide.step_{$step}_title") }}</strong>{{ $ui("guide.step_{$step}_help") }}</li>@endforeach</ol></details>

    <nav class="customizer-tools" aria-label="{{ $ui('tools_label') }}">
        @foreach($toolCards as $tool)<a class="customizer-tool" href="{{ $tool['url'] }}"><i class="fa {{ $tool['icon'] }}" aria-hidden="true"></i><span><strong>{{ $tool['label'] }}</strong>{{ $tool['description'] }}</span></a>@endforeach
    </nav>

    <section class="customizer-preview" aria-labelledby="customizer-preview-title">
        <div class="customizer-preview__head"><div><h2 id="customizer-preview-title">{{ $ui('preview.title') }}</h2><p>{{ $ui('preview.help') }}</p></div><div class="customizer-preview__controls" aria-label="{{ $ui('preview.controls') }}"><label class="sr-only" for="customizer-preview-page">{{ $ui('preview.page') }}</label><select id="customizer-preview-page" class="preview-page">@foreach($previewPages as $label => $url)<option value="{{ $url }}">{{ $label }}</option>@endforeach</select><button class="preview-device is-active" type="button" data-preview-width="100%" aria-label="{{ $ui('preview.desktop') }}" aria-pressed="true"><i class="fa fa-desktop" aria-hidden="true"></i></button><button class="preview-device" type="button" data-preview-width="768px" aria-label="{{ $ui('preview.tablet') }}" aria-pressed="false"><i class="fa fa-tablet" aria-hidden="true"></i></button><button class="preview-device" type="button" data-preview-width="390px" aria-label="{{ $ui('preview.mobile') }}" aria-pressed="false"><i class="fa fa-mobile" aria-hidden="true"></i></button><button id="refresh-customizer-preview" class="igf-btn igf-btn--quiet" type="button"><i class="fa fa-refresh" aria-hidden="true"></i> {{ $ui('preview.refresh') }}</button></div></div>
        <div class="customizer-preview__stage"><iframe id="customizer-preview-frame" src="{{ route('frontend.home', ['lang' => $locale]) }}" title="{{ $ui('preview.frame_title') }}"></iframe></div>
    </section>

    <div class="customizer-workspace">
        <aside class="customizer-nav" aria-label="{{ $ui('sections') }}">
            <div class="customizer-nav__search"><label for="customizer-search">{{ $ui('find_setting') }}</label><input id="customizer-search" type="search" placeholder="{{ $ui('find_setting_placeholder') }}"></div>
            @foreach($schema as $groupKey => $group)<a href="#settings-{{ $groupKey }}"><span>{{ $ui("groups.{$groupKey}") }}</span><small>{{ count($group['fields']) }}</small></a>@endforeach
            <form class="customizer-locale" method="GET" action="{{ route('site.settings.index') }}"><label for="settings-locale">{{ $ui('editing_language') }}</label><select id="settings-locale" name="locale" onchange="this.form.submit()">@foreach($locales as $option)<option value="{{ $option->id }}" @selected($option->id === $locale)>{{ $option->name }}</option>@endforeach</select></form>
        </aside>

        <section aria-label="{{ $ui('settings_label') }}">
            <div id="customizer-no-results" class="customizer-no-results"><h2>{{ $ui('no_results') }}</h2><p>{{ $ui('no_results_help') }}</p></div>
            <form id="customizer-form" method="POST" action="{{ route('site.settings.update') }}">
                @csrf @method('PUT')<input type="hidden" name="locale" value="{{ $locale }}"><input type="hidden" name="global_settings_version" value="{{ $globalSettingsVersion }}">
                <div class="customizer-groups">
                    @foreach($schema as $groupKey => $group)
                        <details class="customizer-card" id="settings-{{ $groupKey }}" data-settings-group @if($loop->first || $errors->has("settings.$groupKey.*")) open @endif>
                            <summary><div><h2>{{ $ui("groups.{$groupKey}") }}</h2><p>{{ $group['description'] }}</p></div><i class="fa fa-chevron-down" aria-hidden="true"></i></summary>
                            <div class="customizer-fields">
                                @if($groupKey === 'donation_page')
                                    <div class="donation-builder">
                                        <div><strong>{{ $ui('donation_builder.title') }}</strong><p>{{ $ui('donation_builder.help') }}</p></div>
                                        <div class="donation-builder__actions">@if($canUse('donationType.index'))<a class="igf-btn" href="{{ route('donationType.index') }}"><i class="fa fa-list" aria-hidden="true"></i> {{ $ui('donation_builder.manage_causes') }}</a>@endif<a class="igf-btn igf-btn--quiet" href="{{ route('frontend.donate.index') }}" target="_blank" rel="noopener"><i class="fa fa-external-link" aria-hidden="true"></i> {{ $ui('donation_builder.open_page') }}</a></div>
                                    </div>
                                    <section class="payment-provider-status" aria-labelledby="payment-provider-status-title">
                                        <div class="payment-provider-status__head"><div><strong id="payment-provider-status-title">{{ $ui('payment_status.title') }}</strong><p>{{ $ui('payment_status.help') }}</p></div><span>{{ $ui('payment_status.read_only') }}</span></div>
                                        <ul>
                                            @foreach(($paymentProviderStatuses ?? []) as $provider)
                                                <li @class(['is-ready' => $provider['ready']])><div><strong>{{ $provider['label'] }}</strong><small>{{ $provider['message'] }}</small></div><span><i class="fa {{ $provider['ready'] ? 'fa-check-circle' : 'fa-warning' }}" aria-hidden="true"></i>{{ $provider['status'] }}</span></li>
                                            @endforeach
                                        </ul>
                                    </section>
                                @endif
                                @if($groupKey === 'zakat_calculator')
                                    <div class="donation-builder">
                                        <div><strong>{{ $ui('zakat.title') }}</strong><p>{{ $ui('zakat.help') }}</p></div>
                                        <div class="donation-builder__actions"><a class="igf-btn igf-btn--quiet" href="{{ route('frontend.zakat') }}" target="_blank" rel="noopener"><i class="fa fa-external-link" aria-hidden="true"></i> {{ $ui('zakat.open_page') }}</a></div>
                                    </div>
                                @endif
                                @foreach($group['fields'] as $key => $field)
                                    @php($inputName = "settings[$groupKey][$key]") @php($inputId = "setting-$groupKey-$key") @php($value = old("settings.$groupKey.$key", data_get($values, "$groupKey.$key")))
                                    @if($field['type'] === 'faq_list')
                                        @php($faqItems = is_array($value) ? array_values($value) : [])
                                        <section class="customizer-faq-editor" data-setting-row data-search="{{ strtolower($group['label'].' '.$field['label'].' question answer faq') }}" data-faq-editor data-faq-name="{{ $inputName }}">
                                            <header class="customizer-faq-editor__head">
                                                <div><h3>{{ $field['label'] }}</h3><p>{{ $ui('faq.help') }}</p></div>
                                                <div class="customizer-faq-editor__actions"><span class="customizer-faq-count" data-faq-count>{{ $ui(count($faqItems) === 1 ? 'faq.one_question' : 'faq.many_questions', ['count' => count($faqItems)]) }}</span>@if($canUpdateSettings)<button class="igf-btn" type="button" data-faq-add><i class="fa fa-plus" aria-hidden="true"></i> {{ $ui('faq.add') }}</button>@endif</div>
                                            </header>
                                            <div class="customizer-faq-list" data-faq-items>
                                                @forelse($faqItems as $faqIndex => $faq)
                                                    <article class="customizer-faq-item" data-faq-item>
                                                        <header class="customizer-faq-item__head"><strong data-faq-number>{{ $ui('faq.number', ['number' => $faqIndex + 1]) }}</strong>@if($canUpdateSettings)<div class="customizer-faq-item__actions"><button type="button" data-faq-move="up" aria-label="{{ $ui('faq.move_up', ['number' => $faqIndex + 1]) }}" @disabled($loop->first)><i class="fa fa-arrow-up" aria-hidden="true"></i></button><button type="button" data-faq-move="down" aria-label="{{ $ui('faq.move_down', ['number' => $faqIndex + 1]) }}" @disabled($loop->last)><i class="fa fa-arrow-down" aria-hidden="true"></i></button><button class="is-danger" type="button" data-faq-remove aria-label="{{ $ui('faq.remove', ['number' => $faqIndex + 1]) }}"><i class="fa fa-trash" aria-hidden="true"></i></button></div>@endif</header>
                                                        <div class="customizer-faq-fields">
                                                            <div class="customizer-faq-field"><label for="{{ $inputId }}-{{ $faqIndex }}-question" data-faq-label="question">{{ $ui('faq.question') }}</label><input id="{{ $inputId }}-{{ $faqIndex }}-question" name="{{ $inputName }}[{{ $faqIndex }}][question]" type="text" value="{{ $faq['question'] ?? '' }}" maxlength="500" data-faq-field="question" @disabled(!$canUpdateSettings)></div>
                                                            <div class="customizer-faq-field"><label for="{{ $inputId }}-{{ $faqIndex }}-answer" data-faq-label="answer">{{ $ui('faq.answer') }}</label><textarea id="{{ $inputId }}-{{ $faqIndex }}-answer" name="{{ $inputName }}[{{ $faqIndex }}][answer]" maxlength="5000" data-faq-field="answer" @disabled(!$canUpdateSettings)>{{ $faq['answer'] ?? '' }}</textarea></div>
                                                            <div class="customizer-faq-item__visibility"><input type="hidden" name="{{ $inputName }}[{{ $faqIndex }}][is_active]" value="0" data-faq-field="is_active" @disabled(!$canUpdateSettings)><label class="customizer-check" for="{{ $inputId }}-{{ $faqIndex }}-is_active"><input id="{{ $inputId }}-{{ $faqIndex }}-is_active" type="checkbox" name="{{ $inputName }}[{{ $faqIndex }}][is_active]" value="1" data-faq-field="is_active" @checked(filter_var($faq['is_active'] ?? true, FILTER_VALIDATE_BOOLEAN)) @disabled(!$canUpdateSettings)> {{ $ui('faq.show_publicly') }}</label></div>
                                                        </div>
                                                    </article>
                                                @empty
                                                    <p class="customizer-faq-empty" data-faq-empty>{{ $ui('faq.empty') }}</p>
                                                @endforelse
                                            </div>
                                            @error("settings.$groupKey.$key")<small class="customizer-faq-error">{{ $message }}</small>@enderror
                                            @if($errors->has("settings.$groupKey.$key.*.question"))<small class="customizer-faq-error">{{ $errors->first("settings.$groupKey.$key.*.question") }}</small>@endif
                                            @if($errors->has("settings.$groupKey.$key.*.answer"))<small class="customizer-faq-error">{{ $errors->first("settings.$groupKey.$key.*.answer") }}</small>@endif
                                            @if($canResetSettings)<button class="customizer-reset btn igf-btn igf-btn-tertiary" type="submit" form="reset-{{ $groupKey }}-{{ $key }}"><i class="fa fa-undo" aria-hidden="true"></i> {{ $ui('faq.reset') }}</button>@endif
                                        </section>
                                        @continue
                                    @endif
                                    @if($field['type'] === 'form_field_layout')
                                        @php($layoutItems = app(\App\Services\PublicFormFieldLayoutService::class)->normalize($field, $value))
                                        @php($allowedFields = is_array($field['allowed_fields'] ?? null) ? $field['allowed_fields'] : [])
                                        <section class="customizer-form-layout" data-setting-row data-search="{{ strtolower($group['label'].' '.$field['label'].' form fields order '.collect($allowedFields)->pluck('label')->implode(' ')) }}" data-form-layout-editor data-layout-name="{{ $inputName }}">
                                            <header class="customizer-form-layout__head"><h3>{{ $field['label'] }}</h3><p>{{ $ui('form_layout.help') }}</p></header>
                                            <div class="customizer-form-layout__list" data-form-layout-items>
                                                @foreach($layoutItems as $layoutIndex => $layoutItem)
                                                    @php($layoutKey = $layoutItem['key'])
                                                    @php($fieldRules = $allowedFields[$layoutKey] ?? [])
                                                    @php($alwaysVisible = (bool)($fieldRules['always_visible'] ?? false))
                                                    @php($alwaysRequired = (bool)($fieldRules['always_required'] ?? false))
                                                    <article class="customizer-form-layout__item" data-form-layout-item data-always-visible="{{ $alwaysVisible ? '1' : '0' }}" data-always-required="{{ $alwaysRequired ? '1' : '0' }}">
                                                        <input type="hidden" value="{{ $layoutKey }}" data-layout-field="key" name="{{ $inputName }}[{{ $layoutIndex }}][key]" @disabled(!$canUpdateSettings)>
                                                        <div class="customizer-form-layout__identity"><span data-layout-number>{{ $layoutIndex + 1 }}</span><div><strong>{{ $fieldRules['label'] ?? $layoutKey }}</strong>@if($alwaysVisible || $alwaysRequired)<small>{{ $ui('form_layout.protected') }}</small>@endif</div></div>
                                                        <div class="customizer-form-layout__options">
                                                            <input type="hidden" value="{{ $alwaysVisible ? 1 : 0 }}" data-layout-field="enabled" name="{{ $inputName }}[{{ $layoutIndex }}][enabled]" @disabled(!$canUpdateSettings)>
                                                            <label class="customizer-check"><input type="checkbox" value="1" data-layout-field="enabled" data-layout-enabled @if(!$alwaysVisible) name="{{ $inputName }}[{{ $layoutIndex }}][enabled]" @endif @checked($layoutItem['enabled']) @disabled(!$canUpdateSettings || $alwaysVisible)> {{ $ui('form_layout.show') }}</label>
                                                            <input type="hidden" value="{{ $alwaysRequired ? 1 : 0 }}" data-layout-field="required" name="{{ $inputName }}[{{ $layoutIndex }}][required]" @disabled(!$canUpdateSettings)>
                                                            <label class="customizer-check"><input type="checkbox" value="1" data-layout-field="required" data-layout-required @if(!$alwaysRequired) name="{{ $inputName }}[{{ $layoutIndex }}][required]" @endif @checked($layoutItem['required']) @disabled(!$canUpdateSettings || $alwaysRequired || !$layoutItem['enabled'])> {{ $ui('form_layout.required') }}</label>
                                                        </div>
                                                        @if($canUpdateSettings)<div class="customizer-form-layout__actions"><button type="button" data-layout-move="up" aria-label="{{ $ui('form_layout.move_up', ['number' => $layoutIndex + 1]) }}" @disabled($loop->first)><i class="fa fa-arrow-up" aria-hidden="true"></i></button><button type="button" data-layout-move="down" aria-label="{{ $ui('form_layout.move_down', ['number' => $layoutIndex + 1]) }}" @disabled($loop->last)><i class="fa fa-arrow-down" aria-hidden="true"></i></button></div>@endif
                                                    </article>
                                                @endforeach
                                            </div>
                                            @error("settings.$groupKey.$key")<small class="customizer-faq-error">{{ $message }}</small>@enderror
                                            @if($errors->has("settings.$groupKey.$key.*"))<small class="customizer-faq-error">{{ $errors->first("settings.$groupKey.$key.*") }}</small>@endif
                                            @if($canResetSettings)<button class="customizer-reset btn igf-btn igf-btn-tertiary" type="submit" form="reset-{{ $groupKey }}-{{ $key }}"><i class="fa fa-undo" aria-hidden="true"></i> {{ $ui('form_layout.reset') }}</button>@endif
                                        </section>
                                        @continue
                                    @endif
                                    <div class="customizer-field" data-setting-row data-search="{{ strtolower($group['label'].' '.$field['label'].' '.$key) }}">
                                        @if($field['type'] === 'select')
                                            <div id="{{ $inputId }}-label" class="customizer-field__label">{{ $field['label'] }} @if(isset($field['help']))<small>{{ $field['help'] }}</small>@endif @if(!($field['localized'] ?? false))<small>{{ $ui('used_every_language') }}</small>@endif</div>
                                        @else
                                            <label for="{{ $inputId }}">{{ $field['label'] }} @if(isset($field['help']))<small>{{ $field['help'] }}</small>@endif @if(!($field['localized'] ?? false))<small>{{ $ui('used_every_language') }}</small>@endif</label>
                                        @endif
                                        <div class="customizer-control">
                                            @if(($field['picker'] ?? null) === 'image')
                                                <div class="media-setting"><div class="media-setting__preview"><img id="{{ $inputId }}-preview" src="{{ $value }}" alt="{{ $ui('current_image_preview', ['label' => $field['label']]) }}" onerror="this.style.visibility='hidden'"></div><div class="media-setting__actions">@if($canUpdateSettings)<button class="igf-btn" type="button" data-media-open="{{ $inputId }}"><i class="fa fa-images" aria-hidden="true"></i> {{ $ui('choose_image') }}</button>@endif @if($canUse('media.index'))<a class="igf-btn igf-btn--quiet" href="{{ route('media.index', ['type' => 'image']) }}" target="_blank" rel="noopener">{{ $ui('upload_images') }}</a>@endif<details class="media-setting__advanced"><summary>{{ $ui('advanced_image_address') }}</summary><input id="{{ $inputId }}" name="{{ $inputName }}" type="text" value="{{ $value }}" autocomplete="off" @disabled(!$canUpdateSettings)></details></div></div>
                                            @elseif($field['type'] === 'boolean')
                                                <input type="hidden" name="{{ $inputName }}" value="0" @disabled(!$canUpdateSettings)><label class="customizer-check"><input id="{{ $inputId }}" type="checkbox" name="{{ $inputName }}" value="1" @checked((bool)$value) @disabled(!$canUpdateSettings)> {{ $ui('enabled') }}</label>
                                            @elseif($field['type'] === 'textarea')
                                                <textarea id="{{ $inputId }}" name="{{ $inputName }}" @disabled(!$canUpdateSettings)>{{ $value }}</textarea>
                                            @elseif($field['type'] === 'select')
                                                <fieldset class="customizer-presets" aria-labelledby="{{ $inputId }}-label">
                                                    @foreach($field['options'] as $optionValue => $optionLabel)
                                                        <label class="customizer-preset"><input id="{{ $inputId }}-{{ $optionValue }}" type="radio" name="{{ $inputName }}" value="{{ $optionValue }}" @checked((string)$value === (string)$optionValue) @disabled(!$canUpdateSettings)><span>{{ $optionLabel }}</span></label>
                                                    @endforeach
                                                </fieldset>
                                            @else
                                                <input id="{{ $inputId }}" name="{{ $inputName }}" type="{{ match($field['type']) { 'integer', 'float' => 'number', 'email', 'color', 'date', 'url' => $field['type'], default => 'text' } }}" @if(in_array($field['type'], ['integer', 'float'], true)) min="{{ $field['min'] ?? ($field['type'] === 'integer' ? 1 : 0.01) }}" max="{{ $field['max'] ?? 10000000 }}" step="{{ $field['type'] === 'integer' ? 1 : ($field['step'] ?? '0.01') }}" @endif @if($field['type'] === 'date') max="{{ now()->toDateString() }}" @endif value="{{ $value }}" @disabled(!$canUpdateSettings)>
                                            @endif
                                            @error("settings.$groupKey.$key")<small class="text-danger">{{ $message }}</small>@enderror
                                        </div>
                                        @if($canResetSettings)<button class="customizer-reset btn igf-btn igf-btn-tertiary" type="submit" form="reset-{{ $groupKey }}-{{ $key }}"><i class="fa fa-undo" aria-hidden="true"></i> {{ $ui('reset_default') }}</button>@endif
                                    </div>
                                @endforeach
                            </div>
                        </details>
                    @endforeach
                </div>
            </form>
        </section>
    </div>

    @if($canResetSettings) @foreach($schema as $groupKey => $group) @foreach($group['fields'] as $key => $field)<form id="reset-{{ $groupKey }}-{{ $key }}" method="POST" action="{{ route('site.settings.destroy', [$groupKey, $key]) }}" onsubmit='return confirm(@js($ui('confirm_reset')))'>@csrf @method('DELETE')<input type="hidden" name="locale" value="{{ $locale }}"></form>@endforeach @endforeach @endif
</main>

@if($canUpdateSettings)<div id="media-picker" class="media-modal" role="dialog" aria-modal="true" aria-labelledby="media-picker-title" hidden>
    <div class="media-modal__dialog"><div class="media-modal__head"><h2 id="media-picker-title">{{ $ui('media_picker.title') }}</h2><button class="media-modal__close" type="button" data-media-close aria-label="{{ $ui('media_picker.close') }}"><i class="fa fa-times" aria-hidden="true"></i></button></div><div class="media-modal__search"><label class="sr-only" for="media-picker-search">{{ $ui('media_picker.search') }}</label><input id="media-picker-search" type="search" placeholder="{{ $ui('media_picker.search_placeholder') }}"></div><div class="media-modal__grid" id="media-picker-grid">@forelse($mediaAssets as $asset)<button class="media-choice" type="button" data-media-url="{{ $asset->url }}" data-media-name="{{ strtolower($asset->original_name.' '.$asset->alt_text) }}"><img src="{{ $asset->url }}" alt="{{ $asset->alt_text ?: $asset->original_name }}"><span>{{ $asset->original_name }}</span></button>@empty<div class="media-empty"><p>{{ $ui('media_picker.empty') }}</p>@if($canUse('media.index'))<a class="igf-btn igf-btn--primary" href="{{ route('media.index', ['type' => 'image']) }}">{{ $ui('media_picker.open_library') }}</a>@endif</div>@endforelse</div></div>
</div>@endif
@endsection

@section('custom-js')
<script>
(() => {
    const copy = {
        faq: @json(\App\Support\AdminUi::section('customizer')['faq'] ?? []),
        formLayout: @json(\App\Support\AdminUi::section('customizer')['form_layout'] ?? []),
        unsavedChanges: @json($ui('unsaved_changes')),
        saving: @json($ui('saving')),
        saved: @json($ui('saved')),
        saveFailed: @json($ui('save_failed')),
        connectionFailed: @json($ui('connection_failed')),
        sessionExpired: @json($ui('session_expired')),
        notAllowed: @json($ui('not_allowed')),
        serverFailed: @json($ui('server_failed')),
    };
    const formatCopy = (template, replacements = {}) => Object.entries(replacements).reduce((text, [key, value]) => text.replaceAll(`:${key}`, String(value)), String(template || ''));
    const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[character]));
    const form = document.getElementById('customizer-form'); const status = document.getElementById('customizer-status'); const saveButton = document.getElementById('customizer-save'); const frame = document.getElementById('customizer-preview-frame'); const modal = document.getElementById('media-picker'); const mediaSearch = document.getElementById('media-picker-search'); const clientValidation = document.getElementById('customizer-client-validation'); let dirty = @json($errors->any()); let saving = false; let activeMediaInput = null;
    const designPreviewMaps = {
        font_pairing:{editorial:{'--igf-font-body':"'Hanken Grotesk',Arial,sans-serif",'--igf-font-heading':"'Literata',Georgia,serif"},modern:{'--igf-font-body':"'Hanken Grotesk',Arial,sans-serif",'--igf-font-heading':"'Hanken Grotesk',Arial,sans-serif"},classic:{'--igf-font-body':'Arial,Helvetica,sans-serif','--igf-font-heading':"Georgia,'Times New Roman',serif"}},
        content_width:{compact:{'--igf-content-width':'1040px'},standard:{'--igf-content-width':'1240px'},wide:{'--igf-content-width':'1400px'}},
        heading_size:{compact:{'--igf-heading-1':'clamp(38px,5vw,64px)','--igf-heading-2':'clamp(30px,3.6vw,44px)','--igf-heading-3':'20px','--igf-heading-1-mobile':'36px','--igf-heading-2-mobile':'30px'},standard:{'--igf-heading-1':'clamp(42px,6vw,76px)','--igf-heading-2':'clamp(34px,4vw,52px)','--igf-heading-3':'22px','--igf-heading-1-mobile':'42px','--igf-heading-2-mobile':'34px'},large:{'--igf-heading-1':'clamp(48px,7vw,88px)','--igf-heading-2':'clamp(38px,5vw,62px)','--igf-heading-3':'25px','--igf-heading-1-mobile':'48px','--igf-heading-2-mobile':'38px'}},
        body_text_size:{compact:{'--igf-body-size':'15px','--igf-lead-size':'clamp(17px,1.8vw,19px)','--igf-testimonial-text-size':'clamp(20px,2.5vw,28px)'},standard:{'--igf-body-size':'17px','--igf-lead-size':'clamp(18px,2vw,21px)','--igf-testimonial-text-size':'clamp(22px,3vw,33px)'},large:{'--igf-body-size':'19px','--igf-lead-size':'clamp(20px,2.2vw,24px)','--igf-testimonial-text-size':'clamp(26px,3.4vw,38px)'}},
        section_spacing:{compact:{'--igf-section-block':'clamp(56px,7vw,88px)','--igf-section-mobile':'52px'},standard:{'--igf-section-block':'clamp(72px,9vw,120px)','--igf-section-mobile':'68px'},generous:{'--igf-section-block':'clamp(88px,11vw,144px)','--igf-section-mobile':'82px'}},
        hero_height:{compact:{'--igf-hero-height':'min(650px,78vh)','--igf-hero-height-mobile':'580px'},standard:{'--igf-hero-height':'min(780px,86vh)','--igf-hero-height-mobile':'680px'},tall:{'--igf-hero-height':'min(900px,92vh)','--igf-hero-height-mobile':'780px'}},
        image_size:{compact:{'--igf-card-media-height':'170px'},standard:{'--igf-card-media-height':'230px'},large:{'--igf-card-media-height':'310px'}},
        image_shape:{square:{'--igf-image-aspect':'1 / 1'},portrait:{'--igf-image-aspect':'4 / 5'},landscape:{'--igf-image-aspect':'4 / 3'},wide:{'--igf-image-aspect':'16 / 9'}},
        card_columns:{2:{'--igf-card-columns':'2'},3:{'--igf-card-columns':'3'},4:{'--igf-card-columns':'4'}},
        card_style:{soft:{'--igf-card-border':'#e5e0dc','--igf-card-radius':'var(--igf-card-radius-soft)','--igf-card-shadow':'var(--igf-shadow-card-soft)'},outlined:{'--igf-card-border':'#9f9389','--igf-card-radius':'var(--igf-card-radius-outlined)','--igf-card-shadow':'none'},elevated:{'--igf-card-border':'transparent','--igf-card-radius':'var(--igf-card-radius-elevated)','--igf-card-shadow':'var(--igf-shadow-card-elevated)'}},
        corner_radius:{square:{'--igf-radius-sm':'2px','--igf-radius-md':'4px','--igf-radius-lg':'6px','--igf-card-radius-soft':'4px','--igf-card-radius-outlined':'2px','--igf-card-radius-elevated':'6px'},soft:{'--igf-radius-sm':'7px','--igf-radius-md':'10px','--igf-radius-lg':'16px','--igf-card-radius-soft':'16px','--igf-card-radius-outlined':'10px','--igf-card-radius-elevated':'20px'},rounded:{'--igf-radius-sm':'12px','--igf-radius-md':'18px','--igf-radius-lg':'28px','--igf-card-radius-soft':'24px','--igf-card-radius-outlined':'18px','--igf-card-radius-elevated':'30px'}},
        shadow_density:{flat:{'--igf-shadow-header':'none','--igf-shadow-floating':'none','--igf-shadow-control':'none','--igf-shadow-card-soft':'none','--igf-shadow-card-elevated':'none'},subtle:{'--igf-shadow-header':'0 2px 8px rgba(25,28,29,.07)','--igf-shadow-floating':'0 14px 34px rgba(25,28,29,.16)','--igf-shadow-control':'0 5px 14px rgba(255,117,0,.18)','--igf-shadow-card-soft':'0 5px 18px rgba(25,28,29,.05)','--igf-shadow-card-elevated':'0 16px 36px rgba(25,28,29,.14)'},strong:{'--igf-shadow-header':'0 5px 18px rgba(25,28,29,.16)','--igf-shadow-floating':'0 20px 46px rgba(25,28,29,.24)','--igf-shadow-control':'0 8px 22px rgba(255,117,0,.3)','--igf-shadow-card-soft':'0 9px 28px rgba(25,28,29,.12)','--igf-shadow-card-elevated':'0 24px 50px rgba(25,28,29,.22)'}},
        button_shape:{square:{'--igf-button-radius':'4px'},rounded:{'--igf-button-radius':'10px'},pill:{'--igf-button-radius':'999px'}},
        logo_size:{compact:{'--igf-brand-font-size':'17px','--igf-brand-mark-width':'32px','--igf-brand-mark-size':'27px'},standard:{'--igf-brand-font-size':'20px','--igf-brand-mark-width':'38px','--igf-brand-mark-size':'32px'},large:{'--igf-brand-font-size':'23px','--igf-brand-mark-width':'44px','--igf-brand-mark-size':'38px'}}
    };
    const headerPreviewMaps = {
        presentation:{classic:{'--igf-header-announcement-bg':'#9c4500','--igf-header-announcement-text':'#fff','--igf-header-utility-bg':'#f0f1f2','--igf-header-nav-bg':'#fff','--igf-header-border':'#e5e0dc','--igf-header-text':'#56575b','--igf-header-strong':'#191c1d','--igf-header-hover-bg':'#f6f3f0','--igf-header-active-bg':'#fff3e8','--igf-header-active-text':'#7b3a08'},minimal:{'--igf-header-announcement-bg':'#303236','--igf-header-announcement-text':'#fff','--igf-header-utility-bg':'#fff','--igf-header-nav-bg':'#fff','--igf-header-border':'#e7e9eb','--igf-header-text':'#45464a','--igf-header-strong':'#191c1d','--igf-header-hover-bg':'#f3f4f5','--igf-header-active-bg':'#f3f4f5','--igf-header-active-text':'#303236'},soft:{'--igf-header-announcement-bg':'#813b07','--igf-header-announcement-text':'#fff','--igf-header-utility-bg':'#fff5ed','--igf-header-nav-bg':'#fffaf5','--igf-header-border':'#eadfd6','--igf-header-text':'#5b4a3f','--igf-header-strong':'#28180e','--igf-header-hover-bg':'#ffead8','--igf-header-active-bg':'#ffe5ce','--igf-header-active-text':'#713000'}},
        density:{compact:{'--igf-header-utility-height':'34px','--igf-header-nav-height':'70px','--igf-header-nav-height-mobile':'64px'},standard:{'--igf-header-utility-height':'38px','--igf-header-nav-height':'80px','--igf-header-nav-height-mobile':'70px'},spacious:{'--igf-header-utility-height':'44px','--igf-header-nav-height':'92px','--igf-header-nav-height-mobile':'78px'}},
        sticky:{true:{'--igf-header-position':'sticky'},false:{'--igf-header-position':'relative'}}
    };
    const footerPreviewMaps = {
        presentation:{dark:{'--igf-footer-bg':'#202124','--igf-footer-text':'#d2d3d4','--igf-footer-muted':'#b9bbbd','--igf-footer-strong':'#fff','--igf-footer-heading':'#ff9b48','--igf-footer-link':'#c5c7c8','--igf-footer-link-hover':'#ffb174','--igf-footer-border':'rgba(255,255,255,.12)','--igf-footer-field-border':'rgba(255,255,255,.24)','--igf-footer-field-bg':'#fff','--igf-footer-field-text':'#202124','--igf-footer-social-bg':'rgba(255,255,255,.08)','--igf-footer-badge-bg':'rgba(255,117,0,.12)','--igf-footer-badge-text':'#ffc08c','--igf-footer-success-bg':'rgba(38,129,68,.2)','--igf-footer-success-border':'rgba(119,221,151,.45)','--igf-footer-success-text':'#c9f7d7','--igf-footer-error-bg':'rgba(176,51,40,.22)','--igf-footer-error-border':'rgba(255,138,128,.55)','--igf-footer-error-text':'#ffd8d4'},light:{'--igf-footer-bg':'#f4f1ed','--igf-footer-text':'#45464a','--igf-footer-muted':'#626469','--igf-footer-strong':'#191c1d','--igf-footer-heading':'#813b07','--igf-footer-link':'#45464a','--igf-footer-link-hover':'#713000','--igf-footer-border':'rgba(25,28,29,.16)','--igf-footer-field-border':'rgba(25,28,29,.3)','--igf-footer-field-bg':'#fff','--igf-footer-field-text':'#202124','--igf-footer-social-bg':'rgba(25,28,29,.09)','--igf-footer-badge-bg':'rgba(156,69,0,.1)','--igf-footer-badge-text':'#713000','--igf-footer-success-bg':'#e3f5e8','--igf-footer-success-border':'#438757','--igf-footer-success-text':'#225c33','--igf-footer-error-bg':'#fde8e6','--igf-footer-error-border':'#b34a3f','--igf-footer-error-text':'#7e2e27'},warm:{'--igf-footer-bg':'#3b2114','--igf-footer-text':'#eaded5','--igf-footer-muted':'#d5c2b4','--igf-footer-strong':'#fffaf5','--igf-footer-heading':'#ffb174','--igf-footer-link':'#eaded5','--igf-footer-link-hover':'#ffc99f','--igf-footer-border':'rgba(255,250,245,.17)','--igf-footer-field-border':'rgba(255,250,245,.3)','--igf-footer-field-bg':'#fffaf5','--igf-footer-field-text':'#28180e','--igf-footer-social-bg':'rgba(255,250,245,.1)','--igf-footer-badge-bg':'rgba(255,177,116,.14)','--igf-footer-badge-text':'#ffc99f','--igf-footer-success-bg':'rgba(38,129,68,.28)','--igf-footer-success-border':'rgba(119,221,151,.55)','--igf-footer-success-text':'#d9fbe3','--igf-footer-error-bg':'rgba(176,51,40,.3)','--igf-footer-error-border':'rgba(255,138,128,.65)','--igf-footer-error-text':'#ffe1de'}},
        layout:{columns:{'--igf-footer-shell-width':'1440px','--igf-footer-body-columns':'minmax(220px,.9fr) minmax(0,2.1fr)','--igf-footer-body-legal-columns':'minmax(250px,.85fr) minmax(0,3.15fr)','--igf-footer-body-tablet-columns':'minmax(240px,.82fr) minmax(0,1.8fr)','--igf-footer-content-legal-columns':'minmax(0,2.1fr) minmax(300px,1fr)','--igf-footer-content-tablet-columns':'repeat(2,minmax(0,1fr))'},stacked:{'--igf-footer-shell-width':'1100px','--igf-footer-body-columns':'1fr','--igf-footer-body-legal-columns':'1fr','--igf-footer-body-tablet-columns':'1fr','--igf-footer-content-legal-columns':'1fr','--igf-footer-content-tablet-columns':'1fr'}}
    };
    function newFaqItemMarkup(){return `<article class="customizer-faq-item" data-faq-item><header class="customizer-faq-item__head"><strong data-faq-number>${escapeHtml(copy.faq.new)}</strong><div class="customizer-faq-item__actions"><button type="button" data-faq-move="up" aria-label="${escapeHtml(copy.faq.move_up_generic)}"><i class="fa fa-arrow-up" aria-hidden="true"></i></button><button type="button" data-faq-move="down" aria-label="${escapeHtml(copy.faq.move_down_generic)}"><i class="fa fa-arrow-down" aria-hidden="true"></i></button><button class="is-danger" type="button" data-faq-remove aria-label="${escapeHtml(copy.faq.remove_generic)}"><i class="fa fa-trash" aria-hidden="true"></i></button></div></header><div class="customizer-faq-fields"><div class="customizer-faq-field"><label data-faq-label="question">${escapeHtml(copy.faq.question)}</label><input type="text" maxlength="500" data-faq-field="question"></div><div class="customizer-faq-field"><label data-faq-label="answer">${escapeHtml(copy.faq.answer)}</label><textarea maxlength="5000" data-faq-field="answer"></textarea></div><div class="customizer-faq-item__visibility"><input type="hidden" value="0" data-faq-field="is_active"><label class="customizer-check" data-faq-label="is_active"><input type="checkbox" value="1" data-faq-field="is_active" checked> ${escapeHtml(copy.faq.show_publicly)}</label></div></div></article>`}
    function updateFaqEditor(editor){const container=editor.querySelector('[data-faq-items]');const items=[...container.querySelectorAll('[data-faq-item]')];const prefix=editor.dataset.faqName;items.forEach((item,index)=>{const number=index+1;item.querySelector('[data-faq-number]').textContent=formatCopy(copy.faq.number,{number});item.querySelectorAll('[data-faq-field]').forEach(control=>{const field=control.dataset.faqField;control.name=`${prefix}[${index}][${field}]`;if(control.type!=='hidden')control.id=`setting-contact_page-faqs-${index}-${field}`});item.querySelectorAll('[data-faq-label]').forEach(label=>{label.htmlFor=`setting-contact_page-faqs-${index}-${label.dataset.faqLabel}`});const up=item.querySelector('[data-faq-move="up"]');const down=item.querySelector('[data-faq-move="down"]');const remove=item.querySelector('[data-faq-remove]');if(up){up.disabled=index===0;up.setAttribute('aria-label',formatCopy(copy.faq.move_up,{number}))}if(down){down.disabled=index===items.length-1;down.setAttribute('aria-label',formatCopy(copy.faq.move_down,{number}))}if(remove)remove.setAttribute('aria-label',formatCopy(copy.faq.remove,{number}))});let empty=container.querySelector('[data-faq-empty]');if(!empty){empty=document.createElement('p');empty.className='customizer-faq-empty';empty.dataset.faqEmpty='';empty.textContent=copy.faq.empty;container.prepend(empty)}empty.hidden=items.length>0;const count=editor.querySelector('[data-faq-count]');if(count)count.textContent=formatCopy(items.length===1?copy.faq.one_question:copy.faq.many_questions,{count:items.length});const add=editor.querySelector('[data-faq-add]');if(add)add.disabled=items.length>=50}
    document.querySelectorAll('[data-faq-editor]').forEach(editor=>{updateFaqEditor(editor);editor.addEventListener('input',()=>setDirty(true));editor.addEventListener('change',()=>setDirty(true));editor.addEventListener('click',event=>{const add=event.target.closest('[data-faq-add]');const item=event.target.closest('[data-faq-item]');if(add){const container=editor.querySelector('[data-faq-items]');container.insertAdjacentHTML('beforeend',newFaqItemMarkup());updateFaqEditor(editor);setDirty(true);container.querySelector('[data-faq-item]:last-child [data-faq-field="question"]')?.focus();return}if(!item)return;const items=[...editor.querySelectorAll('[data-faq-item]')];const index=items.indexOf(item);if(event.target.closest('[data-faq-remove]'))item.remove();else if(event.target.closest('[data-faq-move="up"]')&&index>0)item.parentElement.insertBefore(item,items[index-1]);else if(event.target.closest('[data-faq-move="down"]')&&index<items.length-1)item.parentElement.insertBefore(items[index+1],item);else return;updateFaqEditor(editor);setDirty(true)})});
    function updateFormLayoutEditor(editor){const items=[...editor.querySelectorAll('[data-form-layout-item]')];const prefix=editor.dataset.layoutName;items.forEach((item,index)=>{const number=index+1;item.querySelector('[data-layout-number]').textContent=number;item.querySelectorAll('[data-layout-field]').forEach(control=>{const field=control.dataset.layoutField;if(control.matches('input[type="checkbox"]')&&((field==='enabled'&&item.dataset.alwaysVisible==='1')||(field==='required'&&item.dataset.alwaysRequired==='1')))return;control.name=`${prefix}[${index}][${field}]`});const enabled=item.querySelector('[data-layout-enabled]');const required=item.querySelector('[data-layout-required]');if(enabled&&required&&item.dataset.alwaysRequired!=='1'){if(!enabled.checked){required.checked=false;required.disabled=true}else required.disabled=false}const up=item.querySelector('[data-layout-move="up"]');const down=item.querySelector('[data-layout-move="down"]');if(up){up.disabled=index===0;up.setAttribute('aria-label',formatCopy(copy.formLayout.move_up,{number}))}if(down){down.disabled=index===items.length-1;down.setAttribute('aria-label',formatCopy(copy.formLayout.move_down,{number}))}})}
    document.querySelectorAll('[data-form-layout-editor]').forEach(editor=>{updateFormLayoutEditor(editor);editor.addEventListener('change',event=>{if(event.target.matches('[data-layout-enabled],[data-layout-required]')){updateFormLayoutEditor(editor);setDirty(true)}});editor.addEventListener('click',event=>{const button=event.target.closest('[data-layout-move]');if(!button)return;const item=button.closest('[data-form-layout-item]');const items=[...editor.querySelectorAll('[data-form-layout-item]')];const index=items.indexOf(item);if(button.dataset.layoutMove==='up'&&index>0)item.parentElement.insertBefore(item,items[index-1]);else if(button.dataset.layoutMove==='down'&&index<items.length-1)item.parentElement.insertBefore(items[index+1],item);else return;updateFormLayoutEditor(editor);setDirty(true)})});
    function previewSettingValue(group,field){const name=`settings[${group}][${field}]`;const checkbox=form?.querySelector(`input[type="checkbox"][name="${name}"]`);if(checkbox)return String(checkbox.checked);return form?.querySelector(`[name="${name}"]:checked`)?.value}
    function applyPreviewMap(root,group,maps){Object.entries(maps).forEach(([field,presets])=>{const variables=presets[previewSettingValue(group,field)];if(!variables)return;Object.entries(variables).forEach(([property,value])=>root.style.setProperty(property,value))})}
    function applyDesignPreview(){try{const root=frame?.contentDocument?.querySelector('[style*="--igf-primary"]');if(!root)return;applyPreviewMap(root,'design',designPreviewMaps);applyPreviewMap(root,'header',headerPreviewMaps);applyPreviewMap(root,'footer',footerPreviewMaps)}catch(error){/* The preview may still be loading. */}}
    function openHashGroup(){const rawHash=window.location.hash.slice(1);if(!rawHash)return;let id;try{id=decodeURIComponent(rawHash)}catch(error){return}const group=document.getElementById(id);if(group?.matches('[data-settings-group]')){group.open=true;group.scrollIntoView({block:'start'})}}
    function setDirty(value = true){dirty=value;status?.classList.remove('is-success','is-error');if(value&&status)status.textContent=copy.unsavedChanges;status?.classList.toggle('is-visible',value);if(saveButton)saveButton.disabled=!value||saving}
    function setNestedValue(target,segments,value){let cursor=target;segments.forEach((segment,index)=>{if(index===segments.length-1){cursor[segment]=value;return}const nextIsIndex=/^\d+$/.test(segments[index+1]);if(!cursor[segment]||typeof cursor[segment]!=='object')cursor[segment]=nextIsIndex?[]:{};cursor=cursor[segment]})}
    function customizerPayload(data){const payload={};const unsafeKeys=new Set(['__proto__','constructor','prototype']);for(const [name,value] of data.entries()){if(name==='_token'||name==='_method'||typeof value!=='string')continue;const segments=name.match(/[^\[\]]+/g);if(segments?.length&&!segments.some(segment=>unsafeKeys.has(segment)))setNestedValue(payload,segments,value)}return payload}
    function showClientErrors(errors,message=copy.saveFailed){if(!clientValidation)return;const list=clientValidation.querySelector('[data-customizer-errors]');const messages=Object.values(errors||{}).flat().filter(value=>typeof value==='string');list.innerHTML=(messages.length?messages:[message]).map(value=>`<li>${escapeHtml(value)}</li>`).join('');clientValidation.hidden=false;clientValidation.focus();clientValidation.scrollIntoView({block:'center'})}
    async function saveCustomizer(event){
        event.preventDefault();
        if(!form||saving)return;
        const data=new FormData(form);const token=String(data.get('_token')||'');let feedbackShown=false;
        clientValidation?.setAttribute('hidden','');saving=true;if(saveButton)saveButton.disabled=true;
        if(status){status.textContent=copy.saving;status.classList.remove('is-success','is-error');status.classList.add('is-visible')}
        try{
            const response=await fetch(form.action,{method:'PUT',credentials:'same-origin',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':token},body:JSON.stringify(customizerPayload(data))});
            const body=await response.json().catch(()=>({}));
            if(!response.ok||!body.global_settings_version){
                let message=copy.serverFailed;let kind='request';
                if(response.status===422){message=copy.saveFailed;kind='validation'}
                else if(response.status===401||response.status===419){message=copy.sessionExpired;kind='session'}
                else if(response.status===403){message=copy.notAllowed;kind='permission'}
                showClientErrors(response.status===422?body.errors:{},message);feedbackShown=true;
                const requestError=new Error(kind);requestError.displayMessage=message;throw requestError;
            }
            const versionField=form.querySelector('[name="global_settings_version"]');if(versionField)versionField.value=body.global_settings_version;
            dirty=false;if(status){status.textContent=copy.saved;status.classList.remove('is-error');status.classList.add('is-visible','is-success')}
            const url=new URL(frame.src);url.searchParams.set('preview',String(Date.now()));frame.src=url.toString();
        }catch(error){
            const message=error.displayMessage||copy.connectionFailed;dirty=true;
            if(status){status.textContent=message;status.classList.remove('is-success');status.classList.add('is-visible','is-error')}
            if(!feedbackShown)showClientErrors({},message);
        }finally{saving=false;if(saveButton)saveButton.disabled=!dirty}
    }
    setDirty(dirty); form?.querySelectorAll('input:not([type=hidden]),textarea,select').forEach(control=>control.addEventListener(control.matches('select,input[type=checkbox],input[type=color],input[type=radio]')?'change':'input',()=>setDirty(true))); const previewsShellSetting=event=>/settings\[(design|header|footer)\]/.test(event.target?.name||''); form?.addEventListener('input',event=>{if(previewsShellSetting(event))applyDesignPreview()}); form?.addEventListener('change',event=>{if(previewsShellSetting(event))applyDesignPreview()}); form?.addEventListener('submit',saveCustomizer); window.addEventListener('beforeunload',event=>{if(!dirty)return;event.preventDefault();event.returnValue=''})
    frame?.addEventListener('load',applyDesignPreview); document.getElementById('customizer-preview-page')?.addEventListener('change',event=>{frame.src=event.target.value}); document.querySelectorAll('[data-preview-width]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-preview-width]').forEach(item=>{const active=item===button;item.classList.toggle('is-active',active);item.setAttribute('aria-pressed',String(active))});frame.style.width=button.dataset.previewWidth})); document.getElementById('refresh-customizer-preview')?.addEventListener('click',()=>{const url=new URL(frame.src);url.searchParams.set('preview',String(Date.now()));frame.src=url.toString()});
    const settingRows=[...document.querySelectorAll('[data-setting-row]')]; const settingGroups=[...document.querySelectorAll('[data-settings-group]')]; const noResults=document.getElementById('customizer-no-results'); document.getElementById('customizer-search')?.addEventListener('input',event=>{const query=event.target.value.trim().toLowerCase();let visibleCount=0;settingRows.forEach(row=>{const visible=!query||row.dataset.search.includes(query);row.hidden=!visible;if(visible)visibleCount+=1});settingGroups.forEach(group=>{const visible=[...group.querySelectorAll('[data-setting-row]')].some(row=>!row.hidden);group.hidden=!visible;if(query&&visible)group.open=true});noResults?.classList.toggle('is-visible',visibleCount===0)});
    function closeMediaPicker(){if(!modal)return;modal.hidden=true;activeMediaInput=null} document.querySelectorAll('[data-media-open]').forEach(button=>button.addEventListener('click',()=>{activeMediaInput=document.getElementById(button.dataset.mediaOpen);modal.hidden=false;mediaSearch.value='';document.querySelectorAll('.media-choice').forEach(choice=>{choice.hidden=false});window.setTimeout(()=>mediaSearch.focus(),20)})); document.querySelectorAll('[data-media-close]').forEach(button=>button.addEventListener('click',closeMediaPicker)); modal?.addEventListener('click',event=>{if(event.target===modal)closeMediaPicker()}); document.addEventListener('keydown',event=>{if(event.key==='Escape'&&modal&&!modal.hidden)closeMediaPicker()}); mediaSearch?.addEventListener('input',()=>{const query=mediaSearch.value.trim().toLowerCase();document.querySelectorAll('.media-choice').forEach(choice=>{choice.hidden=Boolean(query)&&!choice.dataset.mediaName.includes(query)})}); document.querySelectorAll('.media-choice').forEach(choice=>choice.addEventListener('click',()=>{if(!activeMediaInput)return;activeMediaInput.value=choice.dataset.mediaUrl;activeMediaInput.dispatchEvent(new Event('input',{bubbles:true}));const preview=document.getElementById(activeMediaInput.id+'-preview');if(preview){preview.src=choice.dataset.mediaUrl;preview.style.visibility='visible'}closeMediaPicker()})); window.addEventListener('hashchange',openHashGroup); openHashGroup();
})();
</script>
@endsection
